---
sidebar: sidebar 
permalink: access-data.html 
keywords: access data, mount point, mount volumes, mount clients, on-premises 
summary: Vous pouvez accéder à vos systèmes de fichiers FSX pour ONTAP à partir des environnements sur site en montant des volumes pour les clients NAS et en montant des LUN iSCSI pour les clients SAN. 
---
= Accédez aux données du système de fichiers FSX pour ONTAP
:allow-uri-read: 
:icons: font
:imagesdir: ./media/


[role="lead"]
Vous pouvez accéder à vos systèmes de fichiers FSX pour ONTAP à partir des environnements sur site en montant des volumes pour les clients NAS et en montant des LUN iSCSI pour les clients SAN.

link:https://docs.aws.amazon.com/fsx/latest/ONTAPGuide/supported-fsx-clients.html["Accès aux données"^] Dans la documentation d'Amazon FSX pour NetApp ONTAP, vous trouverez des rubriques sur l'accès aux données à des fins de référence.

Obtenez également le point de montage des volumes en usine de workloads BlueXP .



== Obtenez un point de montage pour les volumes dans l'usine de workloads BlueXP 

Obtenez le point de montage d'un volume pour monter un partage sur un partage CIFS ou un client NFS.

.Étapes
. Connectez-vous à l'aide de l'un des link:https://docs.netapp.com/us-en/workload-setup-admin/console-experiences.html["expériences de la console"^].
. Dans stockage, sélectionnez *accéder à l'inventaire de stockage*.
. Dans l'onglet *FSX pour ONTAP*, sélectionnez le menu à trois points du système de fichiers avec le volume, puis sélectionnez *gérer*.
. Dans la présentation du système de fichiers, sélectionnez l'onglet *volumes*.
. Dans l'onglet volumes, sélectionnez le menu à trois points du volume, puis *actions de base*, puis *commande Afficher montage*.
. Dans la boîte de dialogue de commande Mount, sélectionnez *Copy* pour copier la commande pour le point de montage NFS ou le partage CIFS. Vous entrez la commande copiée dans votre terminal.
. Sélectionnez *Fermer*.




== Se connecter aux clients NAS

* link:https://docs.aws.amazon.com/fsx/latest/ONTAPGuide/attach-linux-client.html["Montez un volume sur des clients Linux"^]
* link:https://docs.aws.amazon.com/fsx/latest/ONTAPGuide/attach-windows-client.html["Montez un volume sur des clients Windows"^]
* link:https://docs.aws.amazon.com/fsx/latest/ONTAPGuide/attach-mac-client.html["Montez un volume sur des clients MacOS"^]




== Se connecter aux clients SAN

* link:https://docs.aws.amazon.com/fsx/latest/ONTAPGuide/mount-iscsi-luns-linux.html["Montez une LUN iSCSI sur des clients Linux"^]
* link:https://docs.aws.amazon.com/fsx/latest/ONTAPGuide/mount-iscsi-windows.html["Montez une LUN iSCSI sur des clients Windows"^]

