---
sidebar: sidebar 
permalink: cascade-replication.html 
keywords: replicate, cascade, cascade replication, cascade deployment, data protection, volume replication, replicate data protection volume 
summary: Répliquez des volumes de protection des données, ou faites en cascade la réplication des données de volume, pour étendre la protection des données aux systèmes tertiaires ou pour migrer vos données. 
---
= Répliquer les volumes de protection des données dans NetApp Workload Factory
:allow-uri-read: 
:icons: font
:imagesdir: ./media/


[role="lead"]
Répliquez des volumes de protection des données, ou faites en cascade la réplication des données de volume, pour étendre la protection des données aux systèmes tertiaires ou pour migrer vos données.

.Description de la tâche
NetApp Workload Factory prend en charge la réplication des volumes de protection des données, également appelés _déploiements en cascade_.  Un _déploiement en cascade_ consiste en une chaîne de relations dans laquelle un volume source est mis en miroir sur un volume secondaire (premier saut) et le volume secondaire est mis en miroir sur un volume tertiaire (deuxième saut).  Si le volume secondaire devient indisponible, vous pouvez synchroniser la relation entre les volumes principal et tertiaire sans effectuer un nouveau transfert de base.

Cette fonctionnalité est prise en charge par FSX pour les systèmes de fichiers ONTAP avec ONTAP version 9.6 et supérieure. Reportez-vous à la link:https://docs.netapp.com/us-en/ontap/data-protection/compatible-ontap-versions-snapmirror-concept.html#snapmirror-disaster-recovery-relationships["Documentation ONTAP pour les versions ONTAP compatibles"^].

En savoir plus sur link:https://docs.netapp.com/us-en/ontap/data-protection/supported-deployment-config-concept.html#how-cascade-deployments-work["fonctionnement des déploiements en cascade"^].

.Avant de commencer
Avant de commencer, tenez compte des points suivants :

* Notez que la resynchronisation des volumes faisant partie d'une configuration en cascade peut prendre plus de temps.
* Si le volume source de la relation est un volume de protection des données et qu'il est la cible d'une autre relation, l'inversion de la relation de réplication n'est pas prise en charge.
* Une réplique d'un volume de protection des données (ou un deuxième saut) est prise en charge. Il n'est pas recommandé de créer une seconde réplique d'un volume de protection des données (ou un troisième saut).


.Étapes
. Connectez-vous à l'aide de l'un des link:https://docs.netapp.com/us-en/workload-setup-admin/console-experiences.html["expériences de la console"^].
. Dans la mosaïque Stockage, sélectionnez *Accéder au stockage*.
. Dans le menu Stockage, sélectionnez *FSx pour ONTAP*.
. Depuis *FSx for ONTAP*, sélectionnez le menu d'actions du système de fichiers qui contient le(s) volume(s) à répliquer, puis sélectionnez *Gérer*.
. Dans la présentation du système de fichiers, sélectionnez l'onglet *volumes*.
. Dans le tableau volumes, sélectionnez un ou plusieurs volumes de protection de données (volumes DP/répliqués), puis sélectionnez *replicate data*.
. Sur la page de données répliquées, sous cible de réplication, indiquez les informations suivantes :
+
.. *FSX pour système de fichiers ONTAP* : sélectionnez les informations d'identification, la région et le nom du système de fichiers FSX pour ONTAP pour le système de fichiers cible FSX pour ONTAP.
.. *Nom de la VM de stockage* : sélectionnez la VM de stockage dans le menu déroulant.
.. *Nom du volume* : le nom du volume cible est généré automatiquement au format suivant `{OriginalVolumeName}_copy`. Vous pouvez utiliser le nom du volume généré automatiquement ou entrer un autre nom de volume.
.. *Cas d’utilisation* : sélectionnez l’un des cas d’utilisation suivants pour la réplication.  En fonction du cas d'utilisation sélectionné, Workload Factory remplit le formulaire avec les valeurs recommandées conformément aux meilleures pratiques.  Vous pouvez accepter les valeurs recommandées ou apporter des modifications au fur et à mesure que vous remplissez le formulaire.
+
*** Migration : transfère vos données vers le système de fichiers cible FSX pour ONTAP
*** Reprise après incident à chaud : assure une haute disponibilité et une reprise après incident rapide pour les workloads stratégiques
*** Reprise après incident des données inactives ou d'archivage :
+
**** Reprise d'activité à froid : utilise des objectifs de délai de restauration (RTO) et des objets de point de restauration (RPO) plus longs pour réduire les coûts
**** Archive : réplique les données pour un stockage et une conformité à long terme


*** Autre


.. *Règle de hiérarchisation* : sélectionnez la règle de hiérarchisation pour les données stockées dans le volume cible. La règle de Tiering est définie par défaut sur la règle de hiérarchisation recommandée pour le cas d'utilisation que vous avez sélectionné.
+
_Balanced (Auto)_ est la stratégie de hiérarchisation par défaut lors de la création d'un volume à l'aide de la console Workload Factory.  Pour plus d'informations sur les politiques de hiérarchisation des volumes, reportez-vous àlink:https://docs.aws.amazon.com/fsx/latest/ONTAPGuide/volume-storage-capacity.html#data-tiering-policy["Capacité de stockage du volume"^] dans la documentation AWS FSx pour NetApp ONTAP .  Notez que Workload Factory utilise des noms basés sur des cas d'utilisation dans la console Workload Factory pour les stratégies de hiérarchisation et inclut les noms de stratégie de hiérarchisation FSx pour ONTAP entre parenthèses.

+
Si vous avez sélectionné le cas d’utilisation de migration, Workload Factory choisit automatiquement de copier la stratégie de hiérarchisation du volume source sur le volume cible.  Vous pouvez désélectionner la copie de la politique de hiérarchisation et sélectionner une politique de hiérarchisation qui s'applique au volume sélectionné pour la réplication.

.. *Taux de transfert max.* : sélectionnez *Limited* et entrez la limite de transfert max. En Mo/s. Vous pouvez également sélectionner *Illimité*.
+
Sans limite, les performances du réseau et des applications peuvent diminuer. Nous recommandons également un taux de transfert illimité pour les systèmes de fichiers FSX pour ONTAP pour les workloads stratégiques, par exemple ceux utilisés principalement pour la reprise d'activité.



. Sous Paramètres de réplication, fournissez les informations suivantes :
+
.. *Intervalle de réplication* : sélectionnez la fréquence à laquelle les instantanés sont transférés du volume source vers le volume cible.
.. *Conservation à long terme* : éventuellement, activez les instantanés pour la conservation à long terme. La conservation à long terme permet aux services de l'entreprise de continuer de fonctionner même en cas de défaillance complète d'un site, ce qui permet aux applications de basculer en toute transparence grâce à une copie secondaire.
+
Les réplications sans rétention à long terme utilisent la stratégie _MirrorAllSnapshots_. L'activation de la rétention à long terme affecte la stratégie _MirrorAndVault_ à la réplication.

+
Si vous activez la conservation à long terme, sélectionnez une règle existante ou créez une nouvelle règle pour définir les snapshots à répliquer et le nombre à conserver.

+

NOTE: Les étiquettes de source et de cible correspondantes sont requises pour la conservation à long terme. Si vous le souhaitez, Workload Factory peut créer des étiquettes manquantes pour vous.

+
*** *Choisissez une stratégie existante* : sélectionnez une stratégie existante dans le menu déroulant.
*** *Créer une nouvelle politique* : fournir ce qui suit :
+
**** *Nom de la stratégie* : entrez un nom de stratégie.
**** Facultatif : activez les snapshots immuables.
+
***** Sélectionnez *Activer les instantanés immuables* pour empêcher la suppression des instantanés pris dans cette stratégie pendant la période de conservation.
***** Définissez la *période de conservation* en nombre d'heures, de jours, de mois ou d'années.


**** *Stratégies Snapshot* : dans le tableau, sélectionnez la fréquence de la règle de snapshot et le nombre de copies à conserver. Vous pouvez sélectionner plusieurs règles de snapshot.






. Sélectionnez *Créer*.


.Résultat
Le ou les volumes répliqués se répliquent et apparaissent dans l'onglet *Replication relations* du système de fichiers cible FSX pour ONTAP.
