---
sidebar: sidebar 
permalink: change-tiering-policy.html 
keywords:  
summary: Modifiez la règle de hiérarchisation pour réallouer les données du niveau de stockage principal hautes performances au niveau de stockage du pool de capacité secondaire. 
---
= Modification de la règle de Tiering d'un volume
:allow-uri-read: 
:icons: font
:imagesdir: ./media/


[role="lead"]
Modifiez la règle de hiérarchisation pour réallouer automatiquement les données du niveau de stockage principal hautes performances au niveau de stockage du pool de capacité secondaire.

.Description de la tâche
Vous pouvez modifier la règle de hiérarchisation d'un volume à tout moment. La règle de hiérarchisation est définie par volume.

Déterminer l'emplacement de stockage de vos données a une incidence sur les économies que vous pouvez réaliser.

FSX pour ONTAP comporte deux niveaux pour le stockage des données de volume :

* *SSD Storage Tier* : ce niveau de stockage primaire est destiné aux données auxquelles vous accédez le plus fréquemment, également appelé _hot_ data. Le stockage des données sur le Tier de stockage primaire est plus coûteux que sur le Tier de stockage secondaire.
* *Niveau de stockage du pool de capacité* : ce niveau de stockage secondaire est destiné aux données archivées ou aux données rarement utilisées, également appelées _Cold_ data.


Pour plus d'informations sur les tiers de stockage, reportez-vous à la section link:https://docs.aws.amazon.com/fsx/latest/ONTAPGuide/managing-storage-capacity.html#storage-tiers["Gestion de la capacité de stockage"^] dans la documentation AWS pour FSX pour NetApp ONTAP.

.Avant de commencer
Avant de modifier la règle de hiérarchisation, vérifiez les quatre règles de hiérarchisation disponibles.

* *Auto* : hiérarchise toutes les données inactives qui incluent les données utilisateur et les snapshots sur le niveau de stockage du pool de capacité pour une période spécifique.
* *Snapshot uniquement* : hiérarchise uniquement les données de snapshot sur le niveau de stockage du pool de capacité.
* *None* : conserve toutes les données de votre volume sur le niveau de stockage primaire.
* *Tout* : marque toutes les données utilisateur et les données d'instantané comme inactives et les stocke dans le niveau de stockage du pool de capacité.


Notez que certaines règles de hiérarchisation ont une période de refroidissement minimale qui définit la durée, ou _journées de refroidissement_, pendant laquelle les données utilisateur d'un volume doivent rester inactives pour que les données soient considérées comme inactives et déplacées vers le niveau de stockage du pool de capacité. La période de refroidissement commence lorsque les données sont écrites sur le disque.

.Étapes
. Connectez-vous à la console Workload Factory.
. Dans stockage, sélectionnez *accéder à l'inventaire de stockage*.
. Dans l'onglet *FSX pour ONTAP*, sélectionnez le menu à trois points du système de fichiers avec le volume à mettre à jour, puis sélectionnez *gérer*.
. Dans la présentation du système de fichiers, sélectionnez l'onglet *volumes*.
. Dans l'onglet volumes, cliquez sur le menu des trois points du volume pour modifier la règle de Tiering pour.
. Sélectionnez *actions avancées*, puis *Modifier la stratégie de hiérarchisation*.
. Sur la page Modifier la règle de hiérarchisation, sélectionnez l'une des règles de hiérarchisation suivantes :
+
** *Auto* : saisissez le nombre de jours de refroidissement.
** *Instantané seulement* : saisissez le nombre de jours de refroidissement.
** *Aucun*
** *Tous*


. Cliquez sur *appliquer*.

