---
sidebar: sidebar 
permalink: change-cifs-share.html 
keywords: cifs, CIFS, cifs share, change cifs share, update cifs share, modify cifs share 
summary: 'Modifiez le partage CIFS d"un volume qui utilise le type de protocole SMB/CIFS.' 
---
= Modifier le partage CIFS d'un volume
:allow-uri-read: 
:icons: font
:imagesdir: ./media/


[role="lead"]
La modification du partage CIFS d'un volume implique de déterminer les utilisateurs et les groupes auxquels accorder l'accès et le type d'accès à leur donner.

.Avant de commencer
Déterminez les utilisateurs ou les groupes auxquels accorder l'accès et le type d'accès à leur donner.

.Étapes
. Connectez-vous au link:https://console.workloads.netapp.com/["Console Workload Factory"^]
. Dans stockage, sélectionnez *accéder à l'inventaire de stockage*.
. Dans l'onglet *FSX pour ONTAP*, sélectionnez le menu à trois points du système de fichiers avec le volume à mettre à jour, puis sélectionnez *gérer*.
. Dans la présentation du système de fichiers, sélectionnez l'onglet *volumes*.
. Dans l'onglet volumes, cliquez sur le menu des trois points du volume pour modifier le partage SMB de.
. Sélectionnez *actions avancées*, puis *Modifier le partage CIFS*.
. Sur la page Modifier le partage CIFS, indiquez les informations suivantes :
+
.. *Utilisateurs ou groupes* : entrez des utilisateurs et des groupes valides. Séparez chaque entrée par un point-virgule «; ».
.. *Autorisations* : sélectionnez *contrôle complet*, *lecture/écriture*, *lecture* ou *pas d'accès*.


. Cliquez sur *appliquer*.

