---
sidebar: sidebar 
permalink: configuration-analysis.html 
keywords: configuration issues, issues, improve, analyze, storage configuration, Amazon FSx for NetApp ONTAP, FSx for ONTAP, recommendation, recommendations 
summary: 'NetApp Workload Factory analyse régulièrement les configurations du système de fichiers Amazon FSx for NetApp ONTAP afin de déterminer s"il existe des problèmes.' 
---
= Analyse de la configuration des systèmes de fichiers FSX pour ONTAP
:allow-uri-read: 
:icons: font
:imagesdir: ./media/


[role="lead"]
NetApp Workload Factory analyse régulièrement les configurations du système de fichiers Amazon FSx for NetApp ONTAP afin de déterminer s'il existe des problèmes.  Lorsque des problèmes sont détectés, Workload Factory vous montre quels sont les problèmes et explique ce qui doit être modifié pour garantir que le stockage de votre système de fichiers atteigne des performances optimales, une rentabilité optimale et la conformité aux meilleures pratiques.

Les fonctionnalités principales comprennent :

* Analyse quotidienne de la configuration
* Validations automatiques des meilleures pratiques
* Observabilité proactive
* Des analyses à l'action
* Framework Advisor bien conçu d'AWS




== État bien conçu

Dans la console Workload Factory, au niveau du système de fichiers, l'état « bien architecturé » est répertorié pour tous les systèmes de fichiers FSx for ONTAP .  Les statuts bien architecturés sont classés comme « problèmes », « non analysés » ou « bien architecturés ».  La sélection du statut bien architecturé vous redirige vers l'onglet du statut bien architecturé dans le système de fichiers où vous pouvez trouver le score bien architecturé, les catégories de configuration et toutes les configurations du système de fichiers.

Score bien conçu:: Le score inclut toutes les configurations actuellement analysées et apparaît sous forme de pourcentage. Un score de 25 % signifie que 25 % des configurations de système de fichiers sont bien conçues.
Catégories de configuration:: Les configurations de système de fichiers sont organisées par catégories, en accord avec les cinq piliers du framework Well-Architected AWS.
+
--
* _Reliability_ : garantit que les charges de travail exécutent correctement et de manière cohérente les fonctions prévues, même en cas de perturbations. Un exemple de configuration est FSX pour les sauvegardes ONTAP.
* _Sécurité_ : met l'accent sur la protection des données, des systèmes et des ressources au moyen d'évaluations des risques et de stratégies d'atténuation.
* _Excellence opérationnelle_ : met l'accent sur la fourniture de l'architecture et de la valeur métier les plus optimales.
* _Optimisation des coûts_ : vise à générer de la valeur commerciale tout en réduisant les coûts.
* _Efficacité des performances_ : se concentre sur l'utilisation efficace des ressources pour répondre aux exigences du système et pour maintenir des performances optimales au fur et à mesure de l'évolution de la demande.


--




== Exigences d'analyse

Pour une analyse complète du système de fichiers, vous devez procéder comme suit :

* Associer un lien.  La connectivité des liens permet à Workload Factory d'analyser toutes les configurations du système de fichiers, telles que la protection des données et les performances.
+
link:https://docs.netapp.com/us-en/workload-fsx-ontap/create-link.html["Apprenez à associer un lien existant ou à créer et associer un nouveau lien"].

* Accordez les autorisations de _visualisation, de planification et d'analyse_ dans votre compte AWS.
+
link:https://docs.netapp.com/us-en/workload-setup-admin/add-credentials.html["Découvrez comment accorder des autorisations à un compte AWS"^]



.Et la suite
link:improve-configurations.html["Implémenter des configurations de système de fichiers bien architecturées"]
