---
sidebar: sidebar 
permalink: create-storage-vm.html 
keywords: create storage VM, create svm 
summary: 'Vous pouvez créer une machine virtuelle de stockage FSx for ONTAP (SVM) pour fournir des services de stockage et de données pour vos charges de travail dans NetApp Workload Factory.' 
---
= Créez une VM de stockage pour un système de fichiers FSX pour ONTAP
:allow-uri-read: 
:icons: font
:imagesdir: ./media/


[role="lead"]
Créez une machine virtuelle de stockage (SVM) pour un système de fichiers FSx for ONTAP afin d'accéder virtuellement aux services de stockage et de données pour vos charges de travail dans NetApp Workload Factory.

.Description de la tâche
Les machines virtuelles de stockage sont des serveurs de fichiers isolés que vous pouvez utiliser pour accéder aux données de chaque charge de travail dans Workload Factory Storage.  Chaque SVM possède ses propres informations d’identification administratives et points de terminaison pour l’administration et l’accès aux données.

Avec les SVM, lorsque vous accédez aux données dans FSX for ONTAP, vos clients et vos postes de travail montent un volume, un partage CIFS/SMB ou une LUN iSCSI hébergée par un SVM à l'aide du terminal du SVM (adresse IP).

.Avant de commencer
Vérifiez le nombre de machines virtuelles de stockage prises en charge par système de fichiers. Pour connaître le nombre maximal de SVM par système de fichiers, reportez-vous à la section link:https://docs.aws.amazon.com/fsx/latest/ONTAPGuide/managing-svms.html#max-svms["Gestion de FSX pour les machines virtuelles de stockage ONTAP"^] dans la documentation AWS.



== Créez une machine virtuelle de stockage

Vous pouvez créer une machine virtuelle de stockage à partir de la console Workload Factory.  Vous pouvez également utiliser les outils suivants disponibles dans Codebox : API REST, CloudFormation et Terraform. link:https://docs.netapp.com/us-en/workload-setup-admin/use-codebox.html#how-to-use-codebox["Découvrez comment utiliser Codebox pour l'automatisation"^] .


NOTE: Lorsque vous utilisez Terraform à partir de Codebox, le code que vous copiez ou téléchargez se cache `fsxadmin` et `vsadmin` passe. Vous devrez saisir à nouveau les mots de passe lorsque vous exécuterez le code.

.Étapes
. Connectez-vous à l'aide de l'un des link:https://docs.netapp.com/us-en/workload-setup-admin/console-experiences.html["expériences de la console"^].
. Dans la mosaïque Stockage, sélectionnez *Accéder au stockage*.
. Dans le menu Stockage, sélectionnez *FSx pour ONTAP*.
. Dans *FSx for ONTAP*, sélectionnez le menu actions du système de fichiers, puis sélectionnez *Gérer*.
. Dans la vue d'ensemble du système de fichiers, sous Machines virtuelles de stockage, sélectionnez *Créer une machine virtuelle de stockage*.
. Sur la page Créer une machine virtuelle de stockage, sous Configuration de la machine virtuelle de stockage, indiquez les informations suivantes :
+
.. *Nom* : entrez un nom pour la machine virtuelle de stockage.
.. *Informations d'identification de la machine virtuelle de stockage* : saisissez un mot de passe pour l'utilisateur de cette machine virtuelle de stockage `vsadmin` ou utilisez les informations d'identification de l'utilisateur du système de fichiers `fsxadmin` .
.. *Style de sécurité du volume racine* : sélectionnez le style de sécurité du volume racine en fonction du type de clients qui accèdent à vos données : UNIX (clients Linux), NTFS (clients Windows) ou Mixed.
.. *Tags*: Vous pouvez éventuellement ajouter jusqu'à 50 tags.


. Sélectionnez *Créer*.

