---
sidebar: sidebar 
permalink: create-volume.html 
keywords: create volume, FSx for ONTAP volume 
summary: Après avoir configuré votre système de fichiers FSx for ONTAP , créez des volumes FSx for ONTAP dans Workload Factory. 
---
= Créer un volume FSx pour ONTAP dans Workload Factory
:allow-uri-read: 
:icons: font
:imagesdir: ./media/


[role="lead"]
Après avoir configuré votre système de fichiers FSx for ONTAP , créez des volumes FSx for ONTAP dans Workload Factory en tant que ressources virtuelles pour regrouper vos données.



== Description de la tâche

Les volumes FSx for ONTAP regroupent les données virtuellement, déterminent la manière dont les données sont stockées et déterminent le type d'accès à vos données. Les volumes ne consomment pas de capacité de stockage du système de fichiers. Les données stockées dans un volume se concentrent principalement sur le stockage SSD. Selon la règle de hiérarchisation du volume, les données peuvent également consommer le stockage du pool de capacité. Vous définissez la taille d'un volume lors de sa création, et vous pouvez en modifier la taille ultérieurement.

Vos volumes peuvent utiliser les protocoles suivants :

* SMB/CIFS : protocole de stockage de fichiers pour les systèmes d'exploitation Windows
* NFS : protocole de stockage de fichiers pour les systèmes d'exploitation Unix
* ISCSI : protocole de stockage en mode bloc


Les points de terminaison S3 peuvent être associés à un volume FSx pour ONTAP . En utilisant un point d'accès S3, vous pouvez accéder aux données de fichiers résidant sur des volumes SMB/CIFS ou NFS via les API AWS S3. Cela vous permet d'intégrer vos données existantes avec GenAI, ML et les analyses des services AWS qui prennent en charge les points d'accès S3.



=== Détails des paramètres de volume

.Fichiers immuables
Cette fonctionnalité, également connue sous le nom de SnapLock, est désactivée par défaut.  L'activation des fichiers immuables empêche la suppression ou l'écrasement des données pendant une période définie.  L'activation de cette fonctionnalité n'est possible que lors de la création du volume.  Une fois la fonctionnalité activée, elle ne peut pas être désactivée.  Il s'agit d'une fonctionnalité premium pour FSx pour ONTAP qui entraîne des frais supplémentaires.  Pour plus d'informations, reportez-vous àlink:https://docs.aws.amazon.com/fsx/latest/ONTAPGuide/how-snaplock-works.html["Fonctionnement de SnapLock"^] dans la documentation Amazon FSx for NetApp ONTAP .

* *Modes de conservation* : Vous pouvez choisir entre deux modes de conservation : _Entreprise_ ou _Conformité_.
+
** En mode _Enterprise_, un fichier immuable, ou SnapLock, l'administrateur peut supprimer un fichier pendant sa période de conservation.
** En mode _Compliance_, un fichier WORM ne peut pas être supprimé avant l'expiration de sa période de conservation. De même, le volume immuable ne peut pas être supprimé tant que les périodes de conservation de tous les fichiers du volume n'ont pas expiré.


* *Période de conservation* : La période de conservation comporte deux paramètres : _politique de conservation_ et _périodes de conservation_.  La _politique de rétention_ définit la durée de conservation des fichiers dans un état WORM immuable.  Vous pouvez spécifier votre propre politique de conservation ou utiliser la politique de conservation par défaut (non spécifiée), qui est de 30 ans.  Les périodes de conservation minimales et maximales définissent la plage de temps autorisée pour le verrouillage des fichiers.
+

NOTE: Même après expiration de la période de conservation, vous ne pouvez pas modifier un fichier WORM. Vous pouvez uniquement la supprimer ou définir une nouvelle période de conservation pour réactiver la protection WORM.

* *Autocommit* : Vous aurez la possibilité d'activer la fonctionnalité d'autocommit.  La fonction de validation automatique valide un fichier dans l'état WORM sur un volume SnapLock si le fichier n'a pas changé pendant la durée de la période de validation automatique.  La fonctionnalité de validation automatique est désactivée par défaut.  Vous devez vous assurer que les fichiers que vous souhaitez valider automatiquement résident sur un volume SnapLock .
* *Suppression privilégiée* : un administrateur SnapLock peut activer la suppression privilégiée sur un volume SnapLock Enterprise pour permettre la suppression d'un fichier avant l'expiration de la période de conservation du fichier.  Cette fonctionnalité est désactivée par défaut.
* *Mode d'ajout de volume* : vous ne pouvez pas modifier les données existantes dans un fichier protégé par WORM.  Cependant, les fichiers immuables vous permettent de maintenir la protection des données existantes à l'aide de fichiers pouvant être ajoutés par WORM.  Par exemple, vous pouvez générer des fichiers journaux ou conserver des données de streaming audio ou vidéo tout en y écrivant des données de manière incrémentielle. link:https://docs.aws.amazon.com/fsx/latest/ONTAPGuide/worm-state.html#worm-state-append["En savoir plus sur le mode d'ajout de volumes"^] dans la documentation Amazon FSx for NetApp ONTAP .




== Avant de commencer

Avant de créer un volume, vérifiez les conditions préalables suivantes :

* Vous devez disposer d'un système de fichiers FSx pour ONTAP dans la console Workload Factory.
* Vous devez disposer d'une VM de stockage.
* Pour l'accès au protocole, procédez comme suit :
+
** Pour configurer l'accès au volume, vous devez associer un lien. link:https://docs.netapp.com/us-en/workload-fsx-ontap/create-link.html["Apprenez à associer un lien existant ou à créer et associer un nouveau lien"]. Une fois le lien associé, revenez à cette opération.
** Vous devez configurer l'accès pour le protocole que vous sélectionnez, SMB/CIFS, NFS ou iSCSI.






== Créer un volume

Vous pouvez créer un volume à l'aide des outils suivants disponibles dans la Codebox : API REST, CloudFormation et Terraform. link:https://docs.netapp.com/us-en/workload-setup-admin/use-codebox.html#how-to-use-codebox["Découvrez comment utiliser Codebox pour l'automatisation"^].


NOTE: Lorsque vous utilisez Terraform à partir de Codebox, le code que vous copiez ou téléchargez se cache `fsxadmin` et `vsadmin` passe. Vous devrez saisir à nouveau les mots de passe lorsque vous exécuterez le code.

.Étapes
. Connectez-vous à l'aide de l'un des link:https://docs.netapp.com/us-en/workload-setup-admin/console-experiences.html["expériences de la console"^].
. Dans la mosaïque Stockage, sélectionnez *Accéder au stockage*.
. Dans le menu Stockage, sélectionnez *FSx pour ONTAP*.
. Depuis *FSx for ONTAP*, sélectionnez le menu d'actions du système de fichiers dans lequel vous souhaitez créer un volume, puis sélectionnez *Créer un volume*.
. Sur la page Créer un volume, sous Détails généraux, fournissez les détails suivants :
+
.. *Nom du volume* : entrez un nom pour le volume.
.. *Nom de la VM de stockage* : vous pouvez éventuellement entrer un nom de VM de stockage.
.. *Volume style* : sélectionnez *FlexVol* ou *FlexGroup* volume.
+
Le style de volume FlexVol est sélectionné par défaut.

+
La taille du volume FlexGroup dépend du nombre de constituants, nécessitant 100 Gio par constituant.

.. *Taille du volume* : entrez la taille du volume et l'unité.
+
Vous pouvez également activer la croissance automatique du volume. Cette option est disponible lorsque vous sélectionnez *File Access* comme type d'accès au volume.

.. *Augmentation automatique du volume* : vous pouvez activer l'augmentation automatique du volume pour augmenter automatiquement sa capacité jusqu'à ce qu'il atteigne sa taille maximale. Cette fonctionnalité s'adapte à l'augmentation de la consommation de données et garantit un fonctionnement ininterrompu.
+
Spécifiez la taille et l'unité de croissance maximales du volume. Vous ne pouvez pas définir la taille de croissance maximale inférieure à la taille du volume actuel

.. *Tags*: Vous pouvez éventuellement ajouter jusqu'à 50 tags.


. Sous accès (uniquement pour les systèmes de fichiers avec des liens associés), fournissez les détails suivants :
+
.. *Type d'accès* : sélectionnez *accès au fichier* ou *accès au bloc*. Les champs supplémentaires permettant de configurer l'accès au volume varient en fonction de votre sélection.
+
*** *Accès aux fichiers* : permet à plusieurs utilisateurs et périphériques autorisés d'accéder au volume à l'aide des protocoles SMB/CIFS, NFS ou Dual (SMB/NFS).
+
Renseignez les champs suivants pour configurer l'accès aux fichiers du volume.



.. *Politique d'exportation NFS* : fournissez les détails suivants pour fournir un accès NFS :
+
... *Contrôle d'accès* : sélectionnez une *règle d'export personnalisée*, une *règle d'export existante* ou un *pas d'accès au volume* dans le menu déroulant.
... *Nom de la politique d'exportation* :
+
Si vous avez sélectionné une export policy personnalisée, sélectionnez un nom de policy existante dans le menu déroulant.

+
Si vous avez sélectionné une export-policy existante, entrez un nouveau nom de policy.

... *Ajouter une règle de stratégie d'exportation* : pour une règle d'export personnalisée, vous pouvez ajouter des règles de stratégie d'exportation à la règle.


.. *Partage SMB/CIFS* : Fournissez les éléments suivants :
+
... *Nom* : saisissez le nom du partage SMB/CIFS pour fournir l'accès.
... *Autorisations* : sélectionnez contrôle total, lecture/écriture, lecture ou aucun accès, puis entrez les utilisateurs ou les groupes séparés par un point-virgule ( ; ). Les utilisateurs ou les groupes sont sensibles à la casse et le domaine de l'utilisateur doit être inclus au format « domaine\nom d'utilisateur ».


.. *Security style* : pour les volumes à double protocole, sélectionnez le style de sécurité UNIX ou NTFS. UNIX est le style de sécurité par défaut pour les volumes à double protocole. Pour obtenir des conseils détaillés sur le mappage des utilisateurs dans ce contexte, reportez-vous à l'article du blog AWS link:https://aws.amazon.com/blogs/storage/enabling-multiprotocol-workloads-with-amazon-fsx-for-netapp-ontap["Prise en charge de workloads multiprotocoles avec Amazon FSX pour NetApp ONTAP"^].
+
*** *Accès en bloc* : permet aux hôtes exécutant des applications métier critiques d'accéder au volume à l'aide du protocole iSCSI. L'accès aux blocs n'est disponible que lorsque le déploiement scale-out du système de fichiers compte six paires haute disponibilité ou moins.
+
Renseignez les champs suivants pour configurer l'accès en bloc au volume.

+
.... *Configuration iSCSI* : fournissez les détails suivants pour configurer iSCSI pour l'accès en bloc au volume.
+
..... Sélectionnez *Créer un nouveau groupe initiateur* ou *mapper un groupe initiateur existant*.
..... Sélectionnez *système d'exploitation hôte* dans le menu déroulant.
..... Entrez un *nom de groupe initiateur* pour un nouveau groupe initiateur.
..... Sous initiateurs hôtes, ajoutez un ou plusieurs initiateurs hôtes iSCSI qualifiés (IQN).






.. *Point d'accès S3* : Vous pouvez, en option, connecter un point d'accès S3 pour accéder aux données du système de fichiers FSx pour ONTAP résidant sur des volumes NFS ou SMB/CIFS via les API AWS S3. Seul le type d'accès aux fichiers est pris en charge. Veuillez fournir les détails suivants :
+
*** *Nom du point d'accès S3* : Saisissez le nom du point d'accès S3.
*** *Utilisateur* : sélectionnez un utilisateur existant avec accès au volume ou créez un nouvel utilisateur.
*** *Type d'utilisateur* : sélectionnez *UNIX* ou *Windows* comme type d'utilisateur.




. Sous efficacité et protection, fournissez les détails suivants :
+
.. *Efficacité de stockage* : activée par défaut. Sélectionnez pour désactiver cette fonctionnalité.
+
ONTAP atteint une efficacité de stockage grâce aux fonctionnalités de déduplication et de compression. La déduplication permet d'éliminer les blocs de données dupliqués. La compression des données compresse les blocs de données afin de réduire la quantité d'espace de stockage physique nécessaire.

.. *Politique d'instantanés* : sélectionnez la stratégie d'instantanés pour spécifier la fréquence et la rétention des instantanés.
+
Voici les règles par défaut d'AWS. Pour les stratégies d'instantanés personnalisées, vous devez link:link:https://docs.netapp.com/us-en/workload-fsx-ontap/create-link.html["associer un lien"] .

+
`default`:: Cette règle crée automatiquement des snapshots selon le planning suivant, avec les plus anciennes copies supprimées pour faire de la place pour les nouvelles copies :
+
--
*** Six snapshots par heure au maximum ont pris cinq minutes au-delà de l'heure.
*** Un maximum de deux clichés quotidiens pris du lundi au samedi à 10 minutes après minuit.
*** Un maximum de deux instantanés hebdomadaires pris chaque dimanche à 15 minutes après minuit.
+

NOTE: Les heures des snapshots sont basées sur le fuseau horaire du système de fichiers, qui est par défaut UTC (temps universel coordonné). Pour plus d'informations sur la modification du fuseau horaire, reportez-vous à la section link:https://library.netapp.com/ecmdocs/ECMP1155684/html/GUID-E26E4C94-DF74-4E31-A6E8-1D2D2287A9A1.html["Affichage et réglage du fuseau horaire du système"^] de la documentation du support NetApp.



--
`default-1weekly`:: Cette règle fonctionne de la même manière que la `default` règle, sauf qu'elle ne conserve qu'un seul snapshot de la planification hebdomadaire.
`none`:: Cette règle ne prend pas de snapshots. Vous pouvez affecter cette règle aux volumes pour empêcher la création automatique de snapshots.


.. *Règle de hiérarchisation* : sélectionnez la règle de hiérarchisation pour les données stockées dans le volume.
+
_Balanced (Auto)_ est la stratégie de hiérarchisation par défaut lors de la création d'un volume à l'aide de la console Workload Factory.  Pour plus d'informations sur les politiques de hiérarchisation des volumes, reportez-vous àlink:https://docs.aws.amazon.com/fsx/latest/ONTAPGuide/volume-storage-capacity.html#data-tiering-policy["Capacité de stockage du volume"^] dans la documentation AWS FSx pour NetApp ONTAP .  Notez que Workload Factory utilise des noms basés sur des cas d'utilisation dans la console Workload Factory pour les stratégies de hiérarchisation et inclut les noms de stratégie de hiérarchisation FSx pour ONTAP entre parenthèses.

.. *Fichiers immuables* : l'activation de la fonctionnalité de fichiers immuables valide de manière permanente les fichiers de ce volume dans un état WORM (écriture unique, lecture multiple) immuable.  Fournissez les détails suivants :
+
... Sélectionnez pour activer *les fichiers immuables alimentés par SnapLock*.
... Cochez la case pour accepter et continuer.
... Sélectionnez *Activer*.
... *Mode rétention* : sélectionnez le mode *entreprise* ou *conformité*.
... *Période de conservation* :
+
**** Sélectionnez la règle de rétention des médias :
+
***** *Non spécifié* : définit la stratégie de rétention sur 30 ans.
***** *Spécifiez la période* : saisissez le nombre de secondes, de minutes, d'heures, de jours, de mois ou d'années pour définir votre propre stratégie de conservation.


**** Sélectionnez les périodes de conservation minimale et maximale :
+
***** *Minimum* : saisissez le nombre de secondes, de minutes, d'heures, de jours, de mois ou d'années pour définir la période de rétention minimale.
***** *Maximum* : saisissez le nombre de secondes, de minutes, d'heures, de jours, de mois ou d'années pour définir la période de rétention maximale.




... *Autocommit* : désactive ou active la validation automatique. Si vous activez la validation automatique, définissez la période de validation automatique.
... *Suppression privilégiée* : Désactiver ou activer.  Si vous activez la suppression privilégiée, un administrateur SnapLock peut supprimer un fichier avant l’expiration de sa période de conservation.
... *Mode d'ajout de volume* : désactiver ou activer. Vous permet d'ajouter du nouveau contenu aux fichiers WORM.


.. *ARP/AI* : NetApp Autonomous Ransomware Protection with AI (ARP/AI) est activé par défaut lorsqu'un lien est associé au système de fichiers. link:https://docs.netapp.com/us-en/workload-fsx-ontap/ransomware-protection.html["En savoir plus sur ARP/AI"]. Acceptez la déclaration pour continuer.
+
Si la fonctionnalité n'est pas disponible, c'est pour l'une des raisons suivantes :

+
*** Un lien n'est pas associé au système de fichiers. link:https://docs.netapp.com/us-en/workload-fsx-ontap/create-link.html["Apprenez à associer un lien existant ou à créer et associer un nouveau lien"]. Une fois le lien associé, revenez à cette opération.
*** Les volumes avec des fichiers immuables et les volumes avec les protocoles iSCSI et NVMe ne sont pas pris en charge pour ARP/AI.
*** Le système de fichiers dispose déjà d’une politique ARP/AI.




. Dans la configuration avancée, fournissez les informations suivantes :
+
.. *Junction path* : entrez l'emplacement dans l'espace de nom de la machine virtuelle de stockage où le volume est monté. Le chemin de jonction par défaut est `/<volume-name>`.
.. *Aggregates list* : uniquement pour les volumes FlexGroup. Ajout ou suppression d'agrégats Le nombre minimal d'agrégats est de un.
.. *Nombre de composants* : uniquement pour les volumes FlexGroup. Entrez le nombre de composants par agrégat. 100 Gio est requis par composant.


. Sélectionnez *Créer*.


.Résultat
Workload Factory lance la création du volume. Une fois créé, le système affiche le nouveau volume dans l'onglet « Volumes ».
