---
sidebar: sidebar 
permalink: create-snapshot.html 
keywords: create snapshot, snapshot 
summary: 'Créez un snapshot manuel d"un volume FSX pour ONTAP en usine de workloads BlueXP . Les snapshots sont des versions instantanées du contenu de votre volume.' 
---
= Créez un snapshot manuel d'un volume FSX pour ONTAP
:allow-uri-read: 
:icons: font
:imagesdir: ./media/


[role="lead"]
Créez un snapshot manuel d'un volume FSX pour ONTAP en usine de workloads BlueXP . Les snapshots sont des versions instantanées du contenu de votre volume.

Les snapshots sont des ressources de volumes qui sont des captures instantanées de vos données qui ne consomment de l'espace que pour les données modifiées. Comme les données évoluent, les snapshots consomment généralement plus d'espace lorsqu'ils sont plus anciens.

Les volumes FSX pour ONTAP utilisent une copie sur écriture « just-in-time » pour que les fichiers non modifiés des snapshots ne consomment aucune de la capacité du volume.


NOTE: Les snapshots ne sont pas des copies de vos données. Si vous souhaitez effectuer des copies de vos données, pensez à utiliser les sauvegardes FSX pour ONTAP ou les fonctionnalités de réplication de volume.

.Avant de commencer
Vous devez associer un lien pour créer un instantané manuel d'un volume. link:https://docs.netapp.com/us-en/workload-fsx-ontap/create-link.html["Apprenez à associer un lien existant ou à créer et associer un nouveau lien"]. Une fois le lien associé, revenez à cette opération.

.Étapes
. Connectez-vous à l'aide de l'un des link:https://docs.netapp.com/us-en/workload-setup-admin/console-experiences.html["expériences de la console"^].
. Dans *stockage*, sélectionnez *aller à l'inventaire de stockage*.
. Dans l'onglet *FSX pour ONTAP*, sélectionnez le menu à trois points du système de fichiers contenant le volume pour lequel créer un snapshot, puis sélectionnez *gérer*.
. Dans la présentation du système de fichiers, sélectionnez l'onglet *volumes*.
. Dans l'onglet *volumes*, sélectionnez le menu à trois points du volume à protéger avec des instantanés.
. Sélectionnez *actions de protection des données*, *instantanés*, puis *Créer un instantané*.
. Dans la boîte de dialogue Créer un snapshot, entrez un nom de snapshot dans le champ *Nom du snapshot*.
. Facultatif : rendez l'instantané immuable pour empêcher la suppression de l'instantané pendant la période de conservation.
+
.. Activer *instantanés immuables*.
.. Définissez la *période de conservation* comme un nombre d'heures, de jours, de mois ou d'années.
.. Acceptez la déclaration concernant les snapshots immuables.


. Sélectionnez *Créer*.


.Résultat
Le volume possède une copie Snapshot.
