---
sidebar: sidebar 
permalink: create-link.html 
keywords: links, add, add links, add link, create link 
summary: Vous pouvez créer et gérer des liens pour fournir une relation de confiance et une connectivité entre un compte Workload Factory et un ou plusieurs systèmes de fichiers FSX for ONTAP. 
---
= Créer un lien
:allow-uri-read: 
:icons: font
:imagesdir: ./media/


[role="lead"]
Vous pouvez créer et gérer des liens pour fournir une relation de confiance et une connectivité entre un compte Workload Factory et un ou plusieurs systèmes de fichiers FSX for ONTAP. Vous pouvez ainsi contrôler et gérer certaines fonctionnalités directement à partir du système de fichiers FSX pour ONTAP qui ne sont pas disponibles via l'API AWS FSX pour ONTAP.

link:links-overview.html["En savoir plus sur les liens"].

.Description de la tâche
La Lambda d'AWS est utilisé pour exécuter le code en réponse aux événements et gérer automatiquement les ressources de calcul requises par ce code. Les liens que vous créez font partie de votre compte NetApp et sont associés à un compte AWS.

Vous pouvez créer un lien dans votre compte lors de la définition d'un système de fichiers FSX pour ONTAP. Ce lien sera utilisé pour ce système de fichiers et il peut être utilisé par d'autres systèmes de fichiers FSX pour ONTAP.

Pour créer le lien, vous devez lancer une pile AWS CloudFormation dans votre compte AWS.

.Avant de commencer
* Vous devez disposer de identifiants pour vous connecter à votre compte AWS.
* Lorsque vous ajoutez un lien à l'aide d'une pile CloudFormation, vous devez disposer des autorisations suivantes dans votre compte AWS :
+
[%collapsible]
====
[source, json]
----
"cloudformation:GetTemplateSummary",
"cloudformation:CreateStack",
"cloudformation:DeleteStack",
"cloudformation:DescribeStacks",
"cloudformation:ListStacks",
"cloudformation:DescribeStackEvents",
"cloudformation:ListStackResources",
"ec2:DescribeSubnets",
"ec2:DescribeSecurityGroups",
"ec2:DescribeVpcs",
"iam:ListRoles",
"iam:GetRolePolicy",
"iam:GetRole",
"iam:DeleteRolePolicy",
"iam:CreateRole",
"iam:DetachRolePolicy",
"iam:PassRole",
"iam:PutRolePolicy",
"iam:DeleteRole",
"iam:AttachRolePolicy",
"lambda:AddPermission",
"lambda:RemovePermission",
"lambda:InvokeFunction",
"lambda:GetFunction",
"lambda:CreateFunction",
"lambda:DeleteFunction",
"lambda:TagResource",
"codestar-connections:GetSyncConfiguration",
"ecr:BatchGetImage",
"ecr:GetDownloadUrlForLayer"
----
====


.Étapes
. Connectez-vous à la console Workload Factory.
. Dans stockage, sélectionnez *accéder à l'inventaire de stockage*.
. Dans l'onglet *FSX pour ONTAP*, sélectionnez le menu à trois points du système de fichiers auquel associer un lien, puis sélectionnez *gérer*.
. Dans la présentation du système de fichiers, sélectionnez *lien associé*.
. Dans la boîte de dialogue associer un lien, sélectionnez *Créer un nouveau lien* et sélectionnez *Continuer*.
. Sur la page Créer un lien, indiquez les informations suivantes :
+
.. *Nom du lien* : saisissez le nom que vous souhaitez utiliser pour ce lien. Le nom doit être unique dans votre compte.
.. *Tags*: Facultatif, ajoutez les balises que vous voulez associer à ce lien pour pouvoir catégoriser plus facilement vos ressources. Par exemple, vous pouvez ajouter une balise qui identifie ce lien comme étant utilisé par FSX pour les systèmes de fichiers ONTAP.
+
Le compte AWS et les informations supplémentaires relatives au compte, à l'emplacement et au groupe de sécurité sont récupérés automatiquement en fonction du système de fichiers FSX pour ONTAP.



. Sélectionnez *rediriger vers CloudFormation*.
+
Une boîte de dialogue expliquant comment créer le lien à partir du service AWS CloudFormation s'affiche.

. Sélectionnez *Continuer* pour ouvrir la console de gestion AWS, puis connectez-vous au compte AWS de ce système de fichiers FSX pour ONTAP.
. Sur la page pile de création rapide, sous fonctionnalités, sélectionnez *Je reconnais que AWS CloudFormation peut créer des ressources IAM*.
+
Notez que trois autorisations sont accordées à Lambda lorsque vous lancez le modèle CloudFormation. Workload Factory utilise ces autorisations lors de l'utilisation de liens.

+
[source, json]
----
"lambda:InvokeFunction",
"lambda:GetFunction",
"lambda:UpdateFunctionCode"
----
. Sélectionnez *Créer pile*, puis *Continuer*.
+
Vous pouvez contrôler l'état de création du lien à partir de la page événements. Cela ne devrait pas prendre plus de 5 minutes.

. Revenez à l'interface Workload Factory et vous verrez que le lien est associé au système de fichiers FSX pour ONTAP.


.Résultat
Le lien que vous avez créé est associé au système de fichiers FSX pour ONTAP.
