---
sidebar: sidebar 
permalink: create-backup.html 
keywords: create backup, volume backup, back up a volume 
summary: 'Créez une sauvegarde manuelle d"un volume dans l"usine de charges de travail BlueXP  en dehors des sauvegardes planifiées régulièrement.' 
---
= Créez une sauvegarde manuelle d'un volume en usine de workloads BlueXP 
:allow-uri-read: 
:icons: font
:imagesdir: ./media/


[role="lead"]
Créez une sauvegarde manuelle d'un volume en dehors des sauvegardes planifiées régulièrement dans l'usine de charges de travail BlueXP .

.Description de la tâche
Les sauvegardes FSX pour ONTAP sont effectuées par volume ; chaque sauvegarde contient donc uniquement les données d'un volume spécifique.

Les sauvegardes FSX pour ONTAP sont incrémentielles, ce qui signifie que seules les données du volume qui ont été modifiées après votre dernière sauvegarde sont enregistrées. Cela réduit le temps nécessaire à la création de la sauvegarde et du stockage requis pour la sauvegarde, ce qui permet de réduire les coûts de stockage en ne dupliquant pas les données.

.Avant de commencer
Pour effectuer des sauvegardes de vos volumes, votre volume et votre système de fichiers doivent disposer d'une capacité de stockage SSD suffisante pour stocker le snapshot de sauvegarde. Lors de la prise d'un snapshot de sauvegarde, la capacité de stockage supplémentaire consommée par l'instantané ne peut pas entraîner une utilisation du volume supérieure à 98 % de l'espace de stockage SSD. Si cela se produit, la sauvegarde échouera.

.Étapes
. Connectez-vous à l'aide de l'un des link:https://docs.netapp.com/us-en/workload-setup-admin/console-experiences.html["expériences de la console"^].
. Dans stockage, sélectionnez *accéder à l'inventaire de stockage*.
. Dans l'onglet *FSX pour ONTAP*, sélectionnez le menu à trois points du système de fichiers avec le volume, puis sélectionnez *gérer*.
. Dans la présentation du système de fichiers, sélectionnez l'onglet *volumes*.
. Dans l'onglet *volumes*, sélectionnez le menu à trois points du volume à sauvegarder.
. Sélectionnez *actions de protection des données*, *FSX pour sauvegarde ONTAP*, puis *sauvegarde manuelle*.
. Dans la boîte de dialogue sauvegarde manuelle, entrez un nom pour la sauvegarde.
. Sélectionnez *Sauvegarder*.

