---
sidebar: sidebar 
permalink: create-snapshot-policy.html 
keywords: create 
summary: Créez une stratégie de snapshot personnalisée pour une machine virtuelle de stockage dans Workload Factory. 
---
= Créer une politique de snapshot pour les machines virtuelles de stockage dans Workload Factory
:allow-uri-read: 
:icons: font
:imagesdir: ./media/


[role="lead"]
Créez une stratégie de snapshot personnalisée pour les machines virtuelles de stockage dans Workload Factory afin de gérer la création et la conservation des snapshots. Une politique de snapshot définit la manière dont le système crée des snapshots pour une machine virtuelle de stockage. Vous pouvez créer une stratégie de snapshot pour une machine virtuelle de stockage dans un système de fichiers FSx for ONTAP . Vous pouvez également partager la politique sur plusieurs machines virtuelles de stockage.

.Description de la tâche
Vous pouvez créer une règle de snapshot personnalisée différente de celle des trois règles de snapshot intégrées pour FSX for ONTAP :

* `default`
* `default-1weekly`
* `none`


Par défaut, chaque volume est associé à la règle de snapshot du système de fichiers `default` . Il est recommandé d'utiliser cette règle pour la plupart des workloads.

La personnalisation d'une stratégie vous permet de spécifier quand créer des snapshots, combien de copies conserver et comment les nommer.

.Avant de commencer
* Une fois la règle de snapshot créée, son association avec la ou les VM de stockage ne peut pas être modifiée, mais vous pouvez toujours ajouter ou supprimer la règle des volumes.
* Avant d'utiliser des snapshots, tenez compte des points suivants :
+
** Pour la plupart des jeux de données, une capacité supplémentaire de 20 % suffit pour conserver les snapshots pendant quatre semaines. À mesure que les données vieillissent, leur utilisation pour les restaurations devient moins probable.
** Le remplacement de toutes les données d'un snapshot consomme une capacité de volume importante, ce qui est important dans la capacité du volume de provisionnement.


* Pour créer une politique de snapshot personnalisée, vous devez associer un lien. link:https://docs.netapp.com/us-en/workload-fsx-ontap/create-link.html["Apprenez à associer un lien existant ou à créer et associer un nouveau lien"]. Une fois le lien associé, revenez à cette opération.


.Étapes
. Connectez-vous à l'aide de l'un des link:https://docs.netapp.com/us-en/workload-setup-admin/console-experiences.html["expériences de la console"^].
. Dans la mosaïque Stockage, sélectionnez *Accéder au stockage*.
. Dans le menu Stockage, sélectionnez *FSx pour ONTAP*.
. Depuis *FSx for ONTAP*, sélectionnez le menu d'actions du système de fichiers avec le volume, puis sélectionnez *Gérer*.
. Dans la présentation du système de fichiers, sélectionnez l'onglet *Storage VMS*.
. Dans l'onglet *VM de stockage*, sélectionnez le menu d'actions du volume à protéger avec des snapshots planifiés, puis *Actions avancées*, puis *Gérer les stratégies de snapshot*.
. Sur la page gestion des règles Snapshot, sélectionnez *Créer une stratégie d'instantanés*.
. Dans le champ *Nom de la stratégie de snapshot*, entrez un nom pour la stratégie de snapshot.
. Si vous le souhaitez, entrez une description de la règle de snapshot.
. Sous *Programme de stratégie et copies*, sélectionnez quand créer des instantanés. Par exemple, toutes les minutes ou toutes les heures.
+
Vous pouvez sélectionner plusieurs fréquences.

. Sous *nombre d'exemplaires*, entrez le nombre d'exemplaires à conserver.
+
Le nombre maximal de copies est de 1,023.

. Facultatif : sous *Naming convention*, entrez un *préfixe* pour la stratégie.
. *Étiquette de conservation* est automatiquement renseignée.
+
Ce libellé fait référence à l'étiquette SnapMirror, ou de réplication utilisée pour sélectionner uniquement les snapshots spécifiés pour la réplication du système de fichiers source vers le système de fichiers cible.

. Facultatif : activez *instantanés immuables* pour tous les horaires dont vous avez besoin, définissez la *période de conservation* pour chaque horaire et acceptez l'instruction pour continuer.
+
L'activation de snapshots immuables verrouille tous les snapshots dans cette politique de snapshots pour empêcher leur suppression pendant la période de conservation.

. *Partager sur les machines virtuelles de stockage* : activé par défaut. Lorsqu'elle est activée, la règle de snapshot est partagée entre toutes les machines virtuelles de stockage du système de fichiers. Désactivez cette option pour créer une stratégie de snapshots pour une seule machine virtuelle de stockage.
. Sélectionnez *Créer*.

