---
sidebar: sidebar 
permalink: create-link.html 
keywords: connect, connection, link, lambda link, associate link, create link, authenticate link 
summary: 'Vous pouvez créer et gérer des liens pour fournir une relation de confiance et une connectivité entre un compte d"usine de workloads BlueXP  et un ou plusieurs systèmes de fichiers FSX pour ONTAP.' 
---
= Connectez-vous à un système de fichiers FSX pour ONTAP via un lien Lambda
:allow-uri-read: 
:icons: font
:imagesdir: ./media/


[role="lead"]
Pour effectuer des opérations de gestion ONTAP avancées, vous devez établir la connectivité entre votre compte d'usine de workloads et un ou plusieurs systèmes de fichiers FSX pour ONTAP. L'établissement de la connectivité inclut l'association de liaisons Lambda nouvelles et existantes et l'authentification des liaisons. L'association de liens vous permet de contrôler et de gérer certaines fonctionnalités directement à partir du système de fichiers FSX pour ONTAP qui ne sont pas disponibles via l'API AWS FSX pour ONTAP.

link:links-overview.html["En savoir plus sur les liens"].

.Description de la tâche
La Lambda d'AWS est utilisé pour exécuter le code en réponse aux événements et gérer automatiquement les ressources de calcul requises par ce code. Les liens que vous créez font partie de votre compte NetApp et sont associés à un compte AWS.

Vous pouvez créer un lien dans votre compte lors de la définition d'un système de fichiers FSX pour ONTAP. Ce lien sera utilisé pour ce système de fichiers et il peut être utilisé par d'autres systèmes de fichiers FSX pour ONTAP. Vous pouvez également associer ultérieurement un lien à un système de fichiers.

Les liaisons nécessitent une authentification. Vous pouvez utiliser des liens authentiques à l'aide d'informations d'identification stockées dans le service d'informations d'identification d'usine de la charge de travail ou avec vos informations d'identification stockées dans AWS secrets Manager. Une seule méthode d'authentification est prise en charge par liaison. Par exemple, si vous sélectionnez l'authentification de lien avec AWS secrets Manager, vous ne pourrez pas modifier la méthode d'authentification ultérieurement.


NOTE: AWS secrets Manager n'est pas pris en charge lors de l'utilisation d'un connecteur.



== Associer un nouveau lien

L'association d'un nouveau lien inclut la création et l'association de liens.

Vous disposez de deux options pour créer des liens dans ce flux de travail : automatiquement ou manuellement. Pour créer le lien, vous devez lancer une pile AWS CloudFormation dans votre compte AWS.

* Automatiquement : crée un lien avec l'enregistrement automatique via l'usine de charge de travail. Un lien créé automatiquement nécessite des jetons pour l'automatisation de l'usine des charges de travail et le code CloudFormation est de courte durée. Il ne peut être utilisé que pendant six heures.
* Manuellement : crée un lien avec l'enregistrement manuel. Le code CloudFormation persiste et vous laisse plus de temps pour effectuer l'opération. Cette fonctionnalité est particulièrement utile lorsque vous travaillez avec des équipes différentes, telles que Security et DevOps, qui peuvent d'abord avoir besoin d'accorder les autorisations nécessaires pour créer des liens.


.Avant de commencer
* Vous devez considérer l'option de création de lien que vous utiliserez.
* En usine de workloads, vous devez disposer d'au moins un système de fichiers FSX pour ONTAP. Pour découvrir ou créer des systèmes de fichiers FSx pour ONTAP, vous devez disposer d'un compte AWS avec des autorisations pour les instances FSx pour ONTAP et link:https://docs.netapp.com/us-en/workload-setup-admin/add-credentials.html#overview["ajoutez des informations d'identification à l'usine des charges de travail"^] avec des autorisations de _lecture seule_ ou de _lecture/écriture_ pour la gestion du stockage.
* Les ports suivants doivent être ouverts dans le groupe de sécurité associé au système de fichiers FSx for ONTAP pour la connectivité de liaison.
+
** Pour la console de l'usine de charge de travail : port 443 (HTTPS)
** Pour CloudShell : port 22 (SSH)


* Lorsque vous ajoutez un lien à l'aide d'une pile CloudFormation, vous devez disposer des autorisations suivantes dans votre compte AWS :
+
[%collapsible]
====
[source, json]
----
"cloudformation:GetTemplateSummary",
"cloudformation:CreateStack",
"cloudformation:DeleteStack",
"cloudformation:DescribeStacks",
"cloudformation:ListStacks",
"cloudformation:DescribeStackEvents",
"cloudformation:ListStackResources",
"ec2:DescribeSubnets",
"ec2:DescribeSecurityGroups",
"ec2:DescribeVpcs",
"iam:ListRoles",
"iam:GetRolePolicy",
"iam:GetRole",
"iam:DeleteRolePolicy",
"iam:CreateRole",
"iam:DetachRolePolicy",
"iam:PassRole",
"iam:PutRolePolicy",
"iam:DeleteRole",
"iam:AttachRolePolicy",
"lambda:AddPermission",
"lambda:RemovePermission",
"lambda:InvokeFunction",
"lambda:GetFunction",
"lambda:CreateFunction",
"lambda:DeleteFunction",
"lambda:TagResource",
"codestar-connections:GetSyncConfiguration",
"ecr:BatchGetImage",
"ecr:GetDownloadUrlForLayer"
----
====


[role="tabbed-block"]
====
.Créer automatiquement
--
Utilisez CloudFormation pour créer et enregistrer automatiquement le lien dans l'usine de la charge de travail.

.Étapes
. Connectez-vous à l'aide de l'un des link:https://docs.netapp.com/us-en/workload-setup-admin/console-experiences.html["expériences de la console"^].
. Dans stockage, sélectionnez *accéder à l'inventaire de stockage*.
. Dans l'onglet *FSX pour ONTAP*, sélectionnez le menu à trois points du système de fichiers auquel associer un lien, puis sélectionnez *associer lien*.
. Dans la boîte de dialogue associer un lien, sélectionnez *Créer un nouveau lien* et sélectionnez *Continuer*.
. Sur la page Créer un lien, indiquez les informations suivantes :
+
.. *Nom du lien* : saisissez le nom que vous souhaitez utiliser pour ce lien. Le nom doit être unique dans votre compte.
.. *AWS secrets Manager*: Facultatif. Permet à l'usine de workloads d'extraire les informations d'identification d'accès FSX pour ONTAP à partir de votre gestionnaire AWS secrets Manager.
+
La pile de déploiement de lien ajoute le regex de gestionnaire de secrets par défaut suivant à la stratégie d'autorisation Lambda : `arn:aws:secretsmanager:<link_deployment_region>:<link_deployment_account_id>:secret:FSxSecret*`.

+
Vous pouvez créer des secrets en alignement avec les autorisations par défaut ou affecter vos autorisations personnalisées pour la stratégie de liens.

+
*Configurer le point final privé VPC sur AWS secrets Manager* est désactivé par défaut. La sélection de cette option stocke le secret à l'aide du point de terminaison privé VPC au lieu de le stocker localement.

.. *Autorisations de lien* : sélectionnez l'une des options suivantes pour les autorisations de lien :
+
*** *Automatique* : sélectionnez cette option pour que le code AWS CloudFormation ou Terraform crée automatiquement la politique d’autorisation Lambda et le rôle d’exécution.
*** *Fourni par l'utilisateur* : sélectionnez cette option pour attribuer un rôle d'exécution Lambda spécifié et ses politiques associées au lien Lambda. Les autorisations suivantes sont requises pour la politique d'autorisation Lambda .  `secretsmanager:GetSecretValue` l'autorisation n'est requise que si vous avez activé AWS Secrets Manager.
+
[source, json]
----
"ec2:CreateNetworkInterface",
"ec2:DescribeNetworkInterfaces",
"ec2:DeleteNetworkInterface",
"ec2:AssignPrivateIpAddresses",
"ec2:UnassignPrivateIpAddresses",
"secretsmanager:GetSecretValue"
----
+
Saisissez l’ARN du rôle d’exécution Lambda dans la zone de texte.



.. *Tags*: Facultatif, ajoutez les balises que vous voulez associer à ce lien pour pouvoir catégoriser plus facilement vos ressources. Par exemple, vous pouvez ajouter une balise qui identifie ce lien comme étant utilisé par FSX pour les systèmes de fichiers ONTAP.
+
Le compte AWS et les informations supplémentaires relatives au compte, à l'emplacement et au groupe de sécurité sont récupérés automatiquement en fonction du système de fichiers FSX pour ONTAP.



. Sélectionnez *Créer*.
+
La boîte de dialogue rediriger vers CloudFormation s'affiche et explique comment créer le lien à partir du service AWS CloudFormation.

. Sélectionnez *Continuer* pour ouvrir la console de gestion AWS, puis connectez-vous au compte AWS de ce système de fichiers FSX pour ONTAP.
. Sur la page pile de création rapide, sous fonctionnalités, sélectionnez *Je reconnais que AWS CloudFormation peut créer des ressources IAM*.
+
Notez que trois autorisations sont accordées à Lambda lorsque vous lancez le modèle CloudFormation. L'usine de workloads utilise ces autorisations lors de l'utilisation de liens.

+
[source, json]
----
"lambda:InvokeFunction",
"lambda:GetFunction",
"lambda:UpdateFunctionCode"
----
. Sélectionnez *Créer pile*, puis sélectionnez *Continuer*.
+
Vous pouvez contrôler l'état de création du lien à partir de la page événements. Cela ne devrait pas prendre plus de 5 minutes.

. Revenez à l'interface d'usine des workloads et vous verrez que le lien est associé au système de fichiers FSX pour ONTAP.


--
.Créer manuellement
--
Avec cette option, vous extrayez l'ARN du lien depuis AWS CloudFormation et vous le signalez ici. L'usine de charge de travail enregistre manuellement le lien pour vous.

.Étapes
. Connectez-vous à l'aide de l'un des link:https://docs.netapp.com/us-en/workload-setup-admin/console-experiences.html["expériences de la console"^].
. Dans stockage, sélectionnez *accéder à l'inventaire de stockage*.
. Dans l'onglet *FSX pour ONTAP*, sélectionnez le menu à trois points du système de fichiers auquel associer un lien, puis sélectionnez *associer lien*.
. Dans la boîte de dialogue associer un lien, sélectionnez *Créer un nouveau lien* et sélectionnez *Continuer*.
. Sur la page Créer un lien, indiquez les informations suivantes :
+
.. *Nom du lien* : saisissez le nom que vous souhaitez utiliser pour ce lien. Le nom doit être unique dans votre compte.
.. *AWS secrets Manager*: Facultatif. Permet à l'usine de workloads d'extraire les informations d'identification d'accès FSX pour ONTAP à partir de votre gestionnaire AWS secrets Manager.
+
La pile de déploiement de lien ajoute le regex de gestionnaire de secrets par défaut suivant à la stratégie d'autorisation Lambda : `arn:aws:secretsmanager:<link_deployment_region>:<link_deployment_account_id>:secret:FSxSecret*`.

+
Vous pouvez créer des secrets en alignement avec les autorisations par défaut ou affecter vos autorisations personnalisées pour la stratégie de liens.

+
*Configurer le point final privé VPC sur AWS secrets Manager* est désactivé par défaut. La sélection de cette option stocke le secret à l'aide du point de terminaison privé VPC au lieu de le stocker localement.

.. *Autorisations de lien* : sélectionnez l'une des options suivantes pour les autorisations de lien :
+
*** *Automatique* : sélectionnez cette option pour que le code AWS CloudFormation crée automatiquement la stratégie d’autorisation Lambda et le rôle d’exécution.
*** *Fourni par l'utilisateur* : sélectionnez cette option pour attribuer un rôle d'exécution Lambda spécifié et ses politiques associées au lien Lambda. Les autorisations suivantes sont requises pour la politique d'autorisation Lambda .  `secretsmanager:GetSecretValue` l'autorisation n'est requise que si vous avez activé AWS Secrets Manager.
+
[source, json]
----
"ec2:CreateNetworkInterface",
"ec2:DescribeNetworkInterfaces",
"ec2:DeleteNetworkInterface",
"ec2:AssignPrivateIpAddresses",
"ec2:UnassignPrivateIpAddresses"
"secretsmanager:GetSecretValue"
----
+
Saisissez l’ARN du rôle d’exécution Lambda dans la zone de texte.



.. *Tags*: Facultatif, ajoutez les balises que vous voulez associer à ce lien pour pouvoir catégoriser plus facilement vos ressources. Par exemple, vous pouvez ajouter une balise qui identifie ce lien comme étant utilisé par FSX pour les systèmes de fichiers ONTAP.
.. *Enregistrement du lien* : sélectionnez la flèche déroulante pour développer les instructions sur la façon d'enregistrer le lien à partir du service AWS CloudFormation ou à l'aide de Terraform. Suivez les instructions.
+
Notez que trois autorisations sont accordées à Lambda lorsque vous lancez le modèle CloudFormation. L'usine de workloads utilise ces autorisations lors de l'utilisation de liens.

+
[source, json]
----
"lambda:InvokeFunction",
"lambda:GetFunction",
"lambda:UpdateFunctionCode"
----
+
Une fois la pile créée, collez l'ARN Lambda dans la zone de texte.

.. Le compte AWS et les informations supplémentaires relatives au compte, à l'emplacement et au groupe de sécurité sont récupérés automatiquement en fonction du système de fichiers FSX pour ONTAP.


. Sélectionnez *Créer*.
+
Vous pouvez contrôler l'état de création du lien à partir de la page événements. Cela ne devrait pas prendre plus de 5 minutes.

. Revenez à l'interface d'usine des workloads et vous verrez que le lien est associé au système de fichiers FSX pour ONTAP.


--
====
.Résultat
Le lien que vous avez créé est associé au système de fichiers FSX pour ONTAP. Vous pouvez effectuer des opérations ONTAP avancées.



== Associer un lien existant à un système de fichiers FSX pour ONTAP

Après avoir créé un lien, associez-le à un ou plusieurs systèmes de fichiers FSX pour ONTAP.

.Étapes
. Connectez-vous à l'aide de l'un des link:https://docs.netapp.com/us-en/workload-setup-admin/console-experiences.html["expériences de la console"^].
. Dans stockage, sélectionnez *accéder à l'inventaire de stockage*.
. Dans l'onglet *FSX pour ONTAP*, sélectionnez le menu à trois points du système de fichiers auquel associer un lien, puis sélectionnez *associer lien*.
. Dans la page de lien associer, sélectionnez *associer un lien existant*, sélectionnez le lien et sélectionnez *Continuer*.
. Sélectionnez le mode d'authentification.
+
** Workload Factory : saisissez le mot de passe deux fois.
** AWS secrets Manager : entrez le secret ARN.
+
L'ARN secret doit inclure les paires de clés valides suivantes :

+
*** FilesytemID = FSX_filesystem_ID
*** nom d'utilisateur = FSx_user
*** mot de passe = mot_de_passe_utilisateur




. Sélectionnez *appliquer*.


.Résultat
Le lien est associé au système de fichiers FSX pour ONTAP. Vous pouvez effectuer des opérations ONTAP avancées.



== Résolution des problèmes avec l'authentification de liens AWS secrets Manager

Problème:: Le lien ne dispose pas des autorisations nécessaires pour récupérer le secret.
+
--
*Résolution* : ajoutez des autorisations une fois le lien actif. Connectez-vous à la console AWS, recherchez le lien Lambda et modifiez la règle d'autorisation jointe.

--
Problème:: Le secret est introuvable.
+
--
*Résolution* : fournir le code secret ARN correct.

--
Problème:: Le secret n'est pas dans le bon format.
+
--
*Résolution* : accédez à AWS secrets Manager et modifiez le format.

Le secret doit contenir les paires de clés valides suivantes :

* FilesytemID = FSX_filesystem_ID
* nom d'utilisateur = FSx_user
* mot de passe = mot_de_passe_utilisateur


--
Problème:: Le secret ne contient pas d'informations d'identification ONTAP valides pour l'authentification du système de fichiers.
+
--
*Résolution* : fournir des informations d'identification permettant d'authentifier les systèmes de fichiers FSX for ONTAP dans AWS secrets Manager.

--

