---
sidebar: sidebar 
permalink: create-snapshot-policy.html 
keywords: create 
summary: 'Créez une règle Snapshot personnalisée pour une machine virtuelle de stockage dans l"usine de workloads BlueXP .' 
---
= Créez une règle Snapshot pour les machines virtuelles de stockage en usine de workloads BlueXP 
:allow-uri-read: 
:icons: font
:imagesdir: ./media/


[role="lead"]
Créez une règle Snapshot personnalisée pour les machines virtuelles de stockage en usine de workloads BlueXP . Une règle Snapshot définit la façon dont le système crée des snapshots pour une machine virtuelle de stockage. Vous pouvez créer une règle Snapshot pour une machine virtuelle de stockage dans un système de fichiers FSX pour ONTAP. Vous pouvez également partager cette règle entre plusieurs machines virtuelles de stockage.

.Description de la tâche
Vous pouvez créer une règle de snapshot personnalisée différente de celle des trois règles de snapshot intégrées pour FSX for ONTAP :

* `default`
* `default-1weekly`
* `none`


Par défaut, chaque volume est associé à la règle de snapshot du système de fichiers `default` . Il est recommandé d'utiliser cette règle pour la plupart des workloads.

La personnalisation d'une stratégie vous permet de spécifier quand créer des snapshots, combien de copies conserver et comment les nommer.

.Avant de commencer
* Avant d'utiliser des snapshots, tenez compte des points suivants :
+
** Pour la plupart des jeux de données, une capacité supplémentaire de 20 % suffit pour conserver les snapshots pendant quatre semaines. À mesure que les données vieillissent, leur utilisation pour les restaurations devient moins probable.
** Le remplacement de toutes les données d'un snapshot consomme une capacité de volume importante, ce qui est important dans la capacité du volume de provisionnement.


* Pour créer une stratégie de snapshot personnalisée, vous devez link:manage-links.html["associer un lien"]. Si vous n'avez pas de lien existant, link:create-link.html["créer un lien"]. Pour associer un lien dans le système de fichiers, sélectionnez *lien associé* sous *Nom du compte*. Une fois le lien associé, revenez à cette opération.


.Étapes
. Connectez-vous à l'aide de l'un des link:https://docs.netapp.com/us-en/workload-setup-admin/console-experiences.html["expériences de la console"^].
. Dans *stockage*, sélectionnez *aller à l'inventaire de stockage*.
. Dans l'onglet *FSX pour ONTAP*, sélectionnez le menu à trois points du système de fichiers avec le volume, puis sélectionnez *gérer*.
. Dans la présentation du système de fichiers, sélectionnez l'onglet *Storage VMS*.
. Dans l'onglet *Storage VMS*, sélectionnez le menu à trois points du volume à protéger avec les snapshots planifiés, puis cliquez sur *Advanced actions*, puis sur *Manage snapshot policies*.
. Sur la page gestion des règles Snapshot, sélectionnez *Créer une stratégie d'instantanés*.
. Dans le champ *Nom de la stratégie de snapshot*, entrez un nom pour la stratégie de snapshot.
. Si vous le souhaitez, entrez une description de la règle de snapshot.
. Sous *Programme de stratégie et copies*, sélectionnez quand créer des instantanés. Par exemple, toutes les minutes ou toutes les heures.
+
Vous pouvez sélectionner plusieurs fréquences.

. Sous *nombre d'exemplaires*, entrez le nombre d'exemplaires à conserver.
+
Le nombre maximal de copies est de 1,023.

. Facultatif : sous *Naming convention*, entrez un *préfixe* pour la stratégie.
. *Étiquette de conservation* est automatiquement renseignée.
+
Ce libellé fait référence à l'étiquette SnapMirror, ou de réplication utilisée pour sélectionner uniquement les snapshots spécifiés pour la réplication du système de fichiers source vers le système de fichiers cible.

. Facultatif : activez *instantanés immuables* pour tous les horaires dont vous avez besoin, définissez la *période de conservation* pour chaque horaire et acceptez l'instruction pour continuer.
+
L'activation de snapshots immuables verrouille tous les snapshots dans cette politique de snapshots pour empêcher leur suppression pendant la période de conservation.

. *Partager sur les machines virtuelles de stockage* : activé par défaut. Lorsqu'elle est activée, la règle de snapshot est partagée entre toutes les machines virtuelles de stockage du système de fichiers. Désactivez cette option pour créer une stratégie de snapshots pour une seule machine virtuelle de stockage.
. Sélectionnez *Créer*.


.Résultat
La politique Snapshot est créée.
