---
sidebar: sidebar 
permalink: delete-svm.html 
keywords: delete storage vm, delete svm, remove svm 
summary: 'Supprimez une machine virtuelle de stockage (SVM) dont vous n"avez plus besoin dans une configuration de système de fichiers FSX pour ONTAP.' 
---
= Supprime une machine virtuelle de stockage en usine de charges de travail BlueXP 
:allow-uri-read: 
:icons: font
:imagesdir: ./media/


[role="lead"]
Supprimez une machine virtuelle de stockage (SVM) dont vous n'avez plus besoin dans une configuration de système de fichiers FSX pour ONTAP.

.Avant de commencer
Vérifiez les points suivants avant de supprimer une machine virtuelle de stockage :

* S'assurer qu'aucune application n'accède aux données du SVM.
* Supprimer tous les volumes non root attachés au SVM.


.Étapes
. Connectez-vous à l'aide de l'un des link:https://docs.netapp.com/us-en/workload-setup-admin/console-experiences.html["expériences de la console"^].
. Dans stockage, sélectionnez *accéder à l'inventaire de stockage*.
. Dans l'onglet *FSX pour ONTAP*, sélectionnez le menu à trois points du système de fichiers à mettre à jour, puis sélectionnez *gérer*.
. Dans la présentation du système de fichiers, sélectionnez l'onglet *Storage VMS*.
. Dans l'onglet Storage VMs, sélectionnez le menu à trois points de la VM de stockage pour laquelle configurer Active Directory.
. Sélectionnez *Supprimer la VM de stockage*.
. Dans la boîte de dialogue Supprimer la VM de stockage, tapez « delete » pour supprimer la VM de stockage.
. Sélectionnez *Supprimer*.

