---
sidebar: sidebar 
permalink: delete-svm.html 
keywords: delete storage vm, delete svm, remove svm 
summary: 'Supprimez une machine virtuelle de stockage (SVM) dont vous n"avez plus besoin dans une configuration de système de fichiers FSX pour ONTAP.' 
---
= Supprimer une machine virtuelle de stockage dans NetApp Workload Factory
:allow-uri-read: 
:icons: font
:imagesdir: ./media/


[role="lead"]
Supprimez une machine virtuelle de stockage (SVM) dont vous n'avez plus besoin dans une configuration de système de fichiers FSX pour ONTAP.

.Avant de commencer
Vérifiez les points suivants avant de supprimer une machine virtuelle de stockage :

* S'assurer qu'aucune application n'accède aux données du SVM.
* Supprimer tous les volumes non root attachés au SVM.


.Étapes
. Connectez-vous à l'aide de l'un des link:https://docs.netapp.com/us-en/workload-setup-admin/console-experiences.html["expériences de la console"^].
. Dans la mosaïque Stockage, sélectionnez *Accéder au stockage*.
. Dans le menu Stockage, sélectionnez *FSx pour ONTAP*.
. Depuis *FSx for ONTAP*, sélectionnez le menu d'actions du système de fichiers à mettre à jour, puis sélectionnez *Gérer*.
. Dans la présentation du système de fichiers, sélectionnez l'onglet *Storage VMS*.
. Dans l’onglet Machines virtuelles de stockage, sélectionnez le menu d’actions de la machine virtuelle de stockage pour laquelle configurer Active Directory.
. Sélectionnez *Supprimer la VM de stockage*.
. Dans la boîte de dialogue Supprimer la VM de stockage, tapez « delete » pour supprimer la VM de stockage.
. Sélectionnez *Supprimer* pour confirmer.

