---
sidebar: sidebar 
permalink: edit-volume-autogrow.html 
keywords: volume autogrow, increase volume capacity, enable autogrow 
summary: 'Activez la croissance automatique du volume pour permettre à l"usine de workloads BlueXP  de gérer la capacité du volume pour vous. Vous pouvez le désactiver à tout moment.' 
---
= Activez la croissance automatique du volume en usine de la charge de travail BlueXP 
:allow-uri-read: 
:icons: font
:imagesdir: ./media/


[role="lead"]
Activez la croissance automatique du volume pour permettre à l'usine de workloads BlueXP  de gérer la capacité du volume pour vous. Vous pouvez le désactiver à tout moment.

Vous pouvez éventuellement augmenter manuellement la capacité d'un volume à tout moment à l'aide de la link:increase-volume-capacity.html["augmentez la capacité du volume"].


NOTE: La croissance automatique du volume n'est pas prise en charge pour les volumes iSCSI.

.Avant de commencer
Pour activer la croissance automatique du volume, vous devez link:manage-links.html["associer un lien"]. Si vous n'avez pas de lien existant, link:create-link.html["créer un lien"]. Pour associer un lien dans le système de fichiers, sélectionnez *lien associé* sous *Nom du compte*. Une fois le lien associé, revenez à cette opération.

.Étapes
. Connectez-vous à l'aide de l'un des link:https://docs.netapp.com/us-en/workload-setup-admin/console-experiences.html["expériences de la console"^].
. Dans stockage, sélectionnez *accéder à l'inventaire de stockage*.
. Dans l'onglet FSX pour ONTAP, sélectionnez le menu à trois points du système de fichiers avec le volume à mettre à jour, puis sélectionnez *gérer*.
. Dans la présentation du système de fichiers, sélectionnez l'onglet *volumes*.
. Dans l'onglet volumes, sélectionnez le menu à trois points du volume à modifier.
. Sélectionnez *actions de base*, puis *Modifier croissance automatique du volume*.
. Dans la boîte de dialogue Modifier la croissance automatique, activez la croissance automatique du volume.
. Sélectionnez *appliquer*.

