---
sidebar: sidebar 
permalink: edit-volume-autogrow.html 
keywords: volume autogrow, increase volume capacity, enable autogrow 
summary: Activez la croissance automatique du volume pour permettre à Workload Factory de gérer la capacité du volume pour vous. Vous pouvez le désactiver à tout moment. 
---
= Activer la croissance automatique du volume dans l'usine de charge de travail
:allow-uri-read: 
:icons: font
:imagesdir: ./media/


[role="lead"]
Activez la croissance automatique du volume pour permettre à Workload Factory de gérer la capacité du volume pour vous. Vous pouvez le désactiver à tout moment.

Vous pouvez éventuellement augmenter manuellement la capacité d'un volume à tout moment à l'aide de la link:increase-volume-capacity.html["augmentez la capacité du volume"].


NOTE: La croissance automatique du volume n'est pas prise en charge pour les volumes iSCSI.

.Avant de commencer
Pour activer la croissance automatique du volume, vous devez associer un lien. link:https://docs.netapp.com/us-en/workload-fsx-ontap/create-link.html["Apprenez à associer un lien existant ou à créer et associer un nouveau lien"]. Une fois le lien associé, revenez à cette opération.

.Étapes
. Connectez-vous à l'aide de l'un des link:https://docs.netapp.com/us-en/workload-setup-admin/console-experiences.html["expériences de la console"^].
. Dans stockage, sélectionnez *accéder à l'inventaire de stockage*.
. Dans l'onglet FSX pour ONTAP, sélectionnez le menu à trois points du système de fichiers avec le volume à mettre à jour, puis sélectionnez *gérer*.
. Dans la présentation du système de fichiers, sélectionnez l'onglet *volumes*.
. Dans l'onglet volumes, sélectionnez le menu à trois points du volume à modifier.
. Sélectionnez *Actions de base*, puis *Définir l'augmentation automatique du volume*.
. Dans la boîte de dialogue « Définir la croissance automatique », activez la croissance automatique du volume pour augmenter automatiquement sa capacité jusqu'à atteindre sa taille maximale. Cette fonctionnalité s'adapte à l'augmentation de la consommation de données et garantit un fonctionnement ininterrompu.
+
Spécifiez la taille et l'unité de croissance maximales du volume. La taille maximale ne peut pas être inférieure à la taille actuelle du volume.

. Sélectionnez *appliquer*.

