---
sidebar: sidebar 
permalink: enable-auto-capacity-management.html 
keywords: auto capacity, automatic capacity management, file system capacity 
summary: 'L"activation de cette fonctionnalité permet à l"usine de workloads d"ajouter automatiquement du stockage incrémentiel à un système de fichiers FSX pour ONTAP en fonction de l"évolution des besoins en capacité.' 
---
= Activez la gestion automatique de la capacité pour un système de fichiers FSX for ONTAP
:allow-uri-read: 
:icons: font
:imagesdir: ./media/


[role="lead"]
L'activation de la gestion automatique de la capacité permet à BlueXP Workload Factory d'ajouter automatiquement du stockage incrémentiel à un système de fichiers FSx for ONTAP en fonction de l'évolution des besoins en capacité. De plus, cette fonctionnalité élimine la nécessité de surveiller manuellement la capacité et limite le risque de lectures et d'écritures de données applicatives impactantes.

.Description de la tâche
Une analyse du système de fichiers FSX for ONTAP a lieu toutes les 30 minutes pour déterminer si un stockage incrémentiel doit être ajouté et pour vérifier les inodes de volume disponibles, ou le nombre maximal de fichiers et de dossiers dans un volume, de sorte que leur nombre augmente en fonction des seuils configurés pour la gestion automatique de la capacité.

Un seul compte peut gérer cette fonction.

La capacité de stockage SSD maximale pour tous les systèmes de fichiers FSX for ONTAP est de 524,288 Gio. Pour demander une augmentation de quota, reportez-vous link:https://docs.aws.amazon.com/fsx/latest/ONTAPGuide/limits.html["Quotas"^] à dans la documentation AWS FSX pour NetApp ONTAP.

.Avant de commencer
Avant de commencer, tenez compte des points suivants :

* Vous devez disposer d'informations d'identification avec des autorisations de lecture/écriture dans Workload Factory pour effectuer cette tâche.
* Pour vous assurer que les inodes de volume augmentent avec la capacité de stockage, vous devez associer un lien. link:https://docs.netapp.com/us-en/workload-fsx-ontap/create-link.html["Apprenez à associer un lien existant ou à créer et associer un nouveau lien"]. Une fois le lien associé, revenez à cette opération.
* N'activez pas cette fonctionnalité pendant la migration des données, car AWS impose une période de refroidissement minimale de six heures entre chaque augmentation de capacité SSD. Cette restriction peut retarder les ajustements ; planifiez donc en conséquence.


.Étapes
. Connectez-vous à l'aide de l'un des link:https://docs.netapp.com/us-en/workload-setup-admin/console-experiences.html["expériences de la console"^].
. Dans stockage, sélectionnez *aller à stock de stockage*.
. Dans l'onglet *FSX pour ONTAP*, sélectionnez le menu à trois points du système de fichiers pour activer la gestion automatique de la capacité pour.
. Sélectionnez *gérer*.
. Sous informations, sélectionnez l'icône en forme de crayon en regard de *gestion automatique de la capacité*. L'icône en forme de crayon apparaît à côté de la flèche de la liste déroulante lorsque la souris survole la ligne *gestion automatique de la capacité*.
. Dans la boîte de dialogue *gestion automatique de la capacité*, indiquez les éléments suivants :
+
.. *Informations d'identification* : sélectionnez les informations d'identification avec les autorisations _automate_ dans le menu déroulant.
.. Sélectionnez le bouton Activer pour *Activer la gestion automatique de la capacité*.
+
Vous pouvez également désactiver la fonction. Si vous devez augmenter la capacité du système de fichiers, vous devez d'abord désactiver la gestion automatique de la capacité.

.. *Augmentation du seuil* : entrez la taille maximale du système de fichiers FSX pour ONTAP.
.. *Augmentation incrémentale* : entrez le pourcentage pour augmenter la capacité progressivement.
.. Facultatif : activez la gestion automatique des inodes pour vous assurer que la capacité des fichiers par volume augmente en augmentant le nombre d'inodes (fichiers) jusqu'à la limite autorisée.


. Sélectionnez *appliquer*.


.Résultat
Une analyse du système de fichiers a lieu toutes les 30 minutes pour déterminer si le système de fichiers a besoin de capacité supplémentaire.
