---
sidebar: sidebar 
permalink: enable-snapshots-long-term.html 
keywords: snapshot long-term retention, enable long-term retention 
summary: 'Activez les snapshots pour la conservation à long terme, ce qui vous permet de répliquer des snapshots spécifiques pour la reprise d"activité à long terme.' 
---
= Activez et modifiez les snapshots pour une conservation à long terme
:allow-uri-read: 
:icons: font
:imagesdir: ./media/


[role="lead"]
En usine de workloads BlueXP , vous pouvez activer les snapshots pour la conservation à long terme, ce qui vous permet de répliquer des snapshots spécifiques pour une reprise d'activité à long terme.

La conservation à long terme permet aux services de l'entreprise de continuer à fonctionner même en cas de défaillance de l'ensemble du site, avec prise en charge du basculement transparent des applications via une copie secondaire.

Les mêmes étapes s'appliquent à l'activation et à la modification de snapshots pour une conservation à long terme.

Lorsqu'un cluster ONTAP sur site est la cible de la relation de réplication, la modification des snapshots pour une conservation à long terme n'est pas prise en charge.

.Étapes
. Connectez-vous à l'aide de l'un des link:https://docs.netapp.com/us-en/workload-setup-admin/console-experiences.html["expériences de la console"^].
. Dans stockage, sélectionnez *accéder à l'inventaire de stockage*.
. Dans l'onglet *FSX pour ONTAP*, sélectionnez le menu à trois points du système de fichiers à mettre à jour, puis sélectionnez *gérer*.
. Dans la présentation du système de fichiers, sélectionnez l'onglet *relations de réplication*.
. Dans l'onglet relations de réplication, sélectionnez le menu à trois points de la planification des relations de réplication à modifier.
. Sélectionnez *Modifier la rétention à long terme*.
. Dans la boîte de dialogue Modifier la rétention à long terme, activez ou désactivez les instantanés pour la conservation à long terme.
. Si vous choisissez de désactiver les instantanés pour la conservation à long terme, sélectionnez *appliquer* pour terminer cette opération.
. Si vous choisissez d'activer les snapshots pour la conservation à long terme, choisissez entre sélectionner une règle existante ou créer une nouvelle règle.
+
.. Pour utiliser une stratégie existante, sélectionnez-la dans le menu déroulant.
.. Pour créer une nouvelle règle, procédez comme suit :
+
... *Nom de la stratégie* : entrez un nom de stratégie.
... *Stratégies Snapshot* : sélectionnez une ou plusieurs stratégies de snapshot.
... *Copies à conserver* : entrez le nombre de copies snapshot à conserver sur le système de fichiers cible.




. Sélectionnez *appliquer*.

