---
sidebar: sidebar 
permalink: explore-savings.html 
keywords: cost, savings, compare costs, EBS, EFS, FSx for Windows file servers FSx for ONTAP 
summary: 'Découvrez les économies que vous réalisez pour vos workloads de stockage dans Amazon Elastic Block Store (EBS), Elastic File System (EFS) et FSX pour les serveurs de fichiers Windows avec AWS FSX pour NetApp ONTAP.' 
---
= Découvrez les économies réalisées grâce à FSX for ONTAP en usine de workloads BlueXP 
:allow-uri-read: 
:icons: font
:imagesdir: ./media/


[role="lead"]
Découvrez les économies que vous réalisez pour vos workloads de stockage utilisant Amazon Elastic Block Store (EBS), Elastic File System (EFS) et FSX pour le serveur de fichiers Windows avec FSX pour NetApp ONTAP.

BlueXP  Workload Factory inclut un calculateur d'économies de stockage afin de comparer les environnements de stockage Amazon à FSX pour ONTAP. Vous pouvez explorer les économies avec ou sans fournir vos identifiants AWS et personnaliser les paramètres de configuration de votre environnement de stockage. Lorsque vous fournissez les informations d'identification AWS, vous pouvez sélectionner une ou plusieurs instances d'Amazon Elastic Block Store, par exemple, et laisser les paramètres d'usine des workloads effectuer la comparaison automatiquement. Que ce soit manuellement ou automatiquement, le calculateur détermine le service de stockage qui offre le coût le plus bas pour vos besoins en stockage.

Si le calculateur de stockage détermine que le stockage le plus économique est FSX pour ONTAP, vous pouvez créer ou enregistrer des configurations FSX pour ONTAP et utiliser la Codebox pour générer des modèles Infrastructure-as-Code indépendamment des autorisations que vous accordez à l'usine de workloads.



== Options de calculatrice

Deux options de calculateur sont disponibles pour comparer les coûts entre vos systèmes et FSX pour ONTAP -- personnalisation et détection automatique pour vos environnements de stockage Amazon.

Explorer les économies via la personnalisation : vous fournissez les paramètres de configuration d'un environnement de stockage, notamment le cas d'utilisation, la région, le nombre de volumes ou de systèmes de fichiers, la quantité de stockage, la fréquence des snapshots, le volume de modifications par Snapshot, les IOPS provisionnées, le débit, etc.

Découvrez les économies réalisées pour les environnements de stockage détectés : l'usine de workloads est liée à vos environnements de stockage AWS existants et extrait les détails du calculateur pour une comparaison automatique. Vous devrez accorder des autorisations d'automatisation pour utiliser le mode automatique. Vous pouvez modifier le cas d'utilisation, mais tous les autres détails sont automatiquement déterminés dans le calcul.

En outre, vous pouvez link:https://docs.netapp.com/us-en/workload-setup-admin/add-credentials.html["Ajoutez des identifiants AWS"^]améliorer la précision de l'analyse de la calculatrice. Sélectionnez *calculer les économies en fonction des ressources existantes*. Vous serez redirigé vers la page Ajouter des informations d'identification. Après avoir ajouté des informations d'identification, sélectionnez les ressources existantes à comparer avec FSX pour ONTAP, puis sélectionnez *Explorer les économies*.



== Explorer les économies via la personnalisation

Suivez les étapes sous l'onglet correspondant à votre sélection de stockage.

[role="tabbed-block"]
====
.Amazon Elastic Block Store (EBS)
--
.Étapes
. Connectez-vous à l'aide de l'un des link:https://docs.netapp.com/us-en/workload-setup-admin/console-experiences.html["expériences de la console"^].
. Dans Storage, sélectionnez *Explore Economies* puis *Amazon Elastic Block Store (EBS)*.
. Dans le calculateur d'économies de stockage, fournissez les informations suivantes :
+
.. *Cas d'utilisation* : obligatoire. Sélectionnez un cas d'utilisation dans le menu déroulant. Le cas d'utilisation sélectionné détermine les caractéristiques du système de fichiers FSX pour ONTAP à des fins de comparaison.
.. *Région*: Facultatif. Sélectionnez la région de votre configuration EBS dans le menu déroulant.
.. *Sélectionnez le type de volume EBS* : facultatif. Sélectionnez le type de volume EBS utilisé pour votre configuration.
.. *Nombre de volumes* : facultatif. Entrez le nombre de volumes de votre configuration EBS.
.. *Quantité de stockage par volume (Tio)* : facultatif. Entrez le montant du stockage par volume en Tio.
.. *Fréquence d'instantané* : facultatif. Sélectionnez la fréquence des snapshots pour votre configuration EBS.
.. *Quantité modifiée par snapshot (Gio)* : facultatif. Pour le stockage snapshot uniquement. Indiquez la quantité modifiée par snapshot en Gio.
.. *IOPS provisionnées par volume* : facultatif. Pour les volumes gp3, io1 et io2. Indiquez les IOPS provisionnées par volume.
.. *Débit (Mio/s)* : facultatif. Pour les volumes gp3 uniquement. Entrer le débit en Mio/s par volume.




--
.Amazon FSX pour serveur de fichiers Windows
--
.Étapes
. Connectez-vous à l'aide de l'un des link:https://docs.netapp.com/us-en/workload-setup-admin/console-experiences.html["expériences de la console"^].
. Dans stockage, sélectionnez *Explorer les économies* puis *Amazon FSX pour Windows File Server*.
. Dans le calculateur d'économies de stockage, fournissez les informations suivantes :
+
.. *Cas d'utilisation* : obligatoire. Sélectionnez un cas d'utilisation dans le menu déroulant. Le cas d'utilisation sélectionné détermine les caractéristiques du système de fichiers FSX pour ONTAP à des fins de comparaison.
.. *Région*: Facultatif. Sélectionnez la région de votre configuration de serveur de fichiers FSX pour Windows dans le menu déroulant.
.. *Type de déploiement* : facultatif. Sélectionnez *zone de disponibilité unique* ou *plusieurs zones de disponibilité*.
.. *Type de stockage* : le type de stockage SSD est sélectionné par défaut.
.. *Capacité de stockage (Tio)* : facultatif. Indiquez la capacité de stockage de la configuration.
.. *Économies de déduplication (%)* : facultatif. Indiquez le pourcentage d'économies de capacité que vous attendez de la déduplication.
.. *Fréquence d'instantané* : facultatif. Sélectionnez la fréquence de snapshot de votre configuration.
.. *Quantité modifiée par snapshot (Gio)* : facultatif. Pour le stockage snapshot uniquement. Indiquez la quantité modifiée par snapshot en Gio.
.. *IOPS SSD provisionnées* : facultatif. Indiquez les IOPS SSD provisionnées.
.. *Débit (Mio/s)* : facultatif. Entrez le débit en Mio/s.




--
.Amazon Elastic File System (EFS)
--
.Étapes
. Connectez-vous à l'aide de l'un des link:https://docs.netapp.com/us-en/workload-setup-admin/console-experiences.html["expériences de la console"^].
. Dans Storage, sélectionnez *Explore Economies* puis *Amazon Elastic File System (EFS)*.
. Dans le calculateur d'économies de stockage, fournissez les informations suivantes :
+
.. *Cas d'utilisation* : obligatoire. Sélectionnez un cas d'utilisation dans le menu déroulant. Le cas d'utilisation sélectionné détermine les caractéristiques du système de fichiers FSX pour ONTAP à des fins de comparaison.
.. *Région*: Facultatif. Sélectionnez la région de votre configuration de serveur de fichiers FSX pour Windows dans le menu déroulant.
.. *Type de système de fichiers* : facultatif. Sélectionnez *régional* ou *une zone*.
.. *Capacité de stockage (Tio)* : facultatif. Entrez la capacité de stockage de la configuration EFS.
.. *Données fréquemment consultées (%)*: Facultatif. Saisissez le pourcentage de données fréquemment utilisées.
.. *Mode de débit* : facultatif. Sélectionnez *débit provisionné* ou *débit élastique*.
.. *Débit (Mio/s)* : facultatif. Entrez le débit en Mio/s.




--
====
Après avoir fourni des détails sur la configuration de votre système de stockage, consultez les calculs et les recommandations fournis sur la page.

De plus, faites défiler jusqu'au bas de la page pour afficher le rapport en sélectionnant l'une des options suivantes :

* *Exporter PDF*
* *Envoyer par courriel*
* *Afficher les calculs*


Pour passer à FSX pour ONTAP, suivez les instructions à <<Déployez FSX pour les systèmes de fichiers ONTAP,Déployez FSX pour les systèmes de fichiers ONTAP>>.



== Découvrez les économies réalisées pour les environnements de stockage détectés

.Avant de commencer
Pour que l'usine de workloads détecte les environnements de stockage Amazon Elastic Block Store (EBS), Elastic File System (EFS) et FSX pour Windows File Server dans votre compte AWS, assurez-vous de bien vouloir utiliser votre compte link:https://docs.netapp.com/us-en/workload-setup-admin/add-credentials.html["accorder des autorisations _read_"^]AWS.


NOTE: Cette option de calculateur ne prend pas en charge les calculs pour les snapshots EBS et les clichés instantanés FSX pour Windows File Server. Lors de l'exploration des économies via la personnalisation, vous pouvez fournir des informations sur les snapshots EBS et FSX pour Windows File Server.

Suivez les étapes sous l'onglet correspondant à votre sélection de stockage.

[role="tabbed-block"]
====
.Amazon Elastic Block Store (EBS)
--
.Étapes
. Connectez-vous à l'aide de l'un des link:https://docs.netapp.com/us-en/workload-setup-admin/console-experiences.html["expériences de la console"^].
. Dans stockage, sélectionnez *accéder à l'inventaire de stockage*.
. Dans l'inventaire du stockage, sélectionnez l'onglet *Explorer les économies*.
. Dans l'onglet *Elastic Block Store (EBS)*, sélectionnez la ou les instances à comparer avec FSX for ONTAP et sélectionnez *Explorer les économies*.
. Le calculateur d'économies de stockage s'affiche. Les caractéristiques suivantes du système de stockage sont pré-remplies en fonction des instances sélectionnées :
+
.. *Cas d'utilisation* : le cas d'utilisation de votre configuration. Vous pouvez modifier le cas d'utilisation si nécessaire.
.. *Volumes sélectionnés* : nombre de volumes dans la configuration EBS
.. *Quantité totale de stockage (Tio)* : quantité de stockage par volume en Tio
.. *Nombre total d'IOPS provisionnées* : pour les volumes gp3, io1 et io2
.. *Débit total (Mio/s)* : pour les volumes gp3 uniquement




--
.Amazon FSX pour serveur de fichiers Windows
--
.Étapes
. Connectez-vous à l'aide de l'un des link:https://docs.netapp.com/us-en/workload-setup-admin/console-experiences.html["expériences de la console"^].
. Dans stockage, sélectionnez *accéder à l'inventaire de stockage*.
. Dans l'inventaire du stockage, sélectionnez l'onglet *Explorer les économies*.
. Dans l'onglet *Amazon FSX pour serveur de fichiers Windows*, sélectionnez la ou les instances à comparer avec FSX pour ONTAP et sélectionnez *Explorer les économies*.
. Le calculateur d'économies de stockage s'affiche. Les caractéristiques suivantes du système de stockage sont pré-remplies en fonction du type de déploiement de l'instance(s) sélectionnée(s) :
+
.. *Cas d'utilisation* : le cas d'utilisation de votre configuration. Vous pouvez modifier le cas d'utilisation si nécessaire.
.. *Systèmes de fichiers sélectionnés
.. *Quantité totale de stockage (Tio)*
.. *IOPS SSD provisionnées*
.. *Débit (Mio/s)*




--
.Amazon Elastic File System (EFS)
--
.Étapes
. Connectez-vous à l'aide de l'un des link:https://docs.netapp.com/us-en/workload-setup-admin/console-experiences.html["expériences de la console"^].
. Dans stockage, sélectionnez *accéder à l'inventaire de stockage*.
. Dans l'inventaire du stockage, sélectionnez l'onglet *Explorer les économies*.
. Dans l'onglet *Elastic File System (EFS)*, sélectionnez la ou les instances à comparer avec FSX for ONTAP et sélectionnez *Explorer les économies*.
. Le calculateur d'économies de stockage s'affiche. Les caractéristiques suivantes du système de stockage sont pré-remplies en fonction des instances sélectionnées :
+
.. *Cas d'utilisation* : le cas d'utilisation de votre configuration. Vous pouvez modifier le cas d'utilisation si nécessaire.
.. *Nombre total de systèmes de fichiers*
.. *Quantité totale de stockage (Tio)*
.. *Débit total provisionné (Mio/s)*
.. *Débit élastique total - lecture (Gio)*
.. *Débit élastique total – écriture (Gio)*




--
====
Après avoir fourni des détails sur la configuration de votre système de stockage, consultez les calculs et les recommandations fournis sur la page.

De plus, faites défiler jusqu'au bas de la page pour afficher le rapport en sélectionnant l'une des options suivantes :

* *Exporter PDF*
* *Envoyer par courriel*
* *Afficher les calculs*




== Déployez FSX pour les systèmes de fichiers ONTAP

Si vous souhaitez passer à FSX pour ONTAP pour réaliser des économies, sélectionnez *Créer* pour créer le(s) système(s) de fichiers directement à partir de l'assistant Créer un système de fichiers FSX pour ONTAP ou sélectionnez *Enregistrer* pour enregistrer la/les configuration(s) recommandée(s) ultérieurement.

Méthodes de déploiement:: En _automate_ mode, vous pouvez déployer le système de fichiers FSX pour ONTAP directement à partir de l'usine de workloads. Vous pouvez également copier le contenu de la fenêtre Codebox et déployer le système à l'aide de l'une des méthodes Codebox.
+
--
En mode _Basic_, vous pouvez copier le contenu de la fenêtre Codebox et déployer le système de fichiers FSX for ONTAP à l'aide de l'une des méthodes Codebox.

--

