---
sidebar: sidebar 
permalink: improve-configurations.html 
keywords: implement best practices, well-architected file system, Amazon FSx for NetApp ONTAP, FSx for ONTAP 
summary: 'L"usine de charges de travail BlueXP  pour les bases de données analyse les configurations de Microsoft SQL Server et fournit des informations et des recommandations pour vous aider à atteindre l"excellence opérationnelle.' 
---
= Implémenter des configurations de système de fichiers bien architecturées
:allow-uri-read: 
:icons: font
:imagesdir: ./media/


[role="lead"]
Grâce aux analyses de configuration et aux recommandations, exploitez Workload Factory pour mettre en œuvre les meilleures pratiques pour vos systèmes de fichiers FSx for ONTAP . Vous pouvez facilement vérifier l'état de l'architecture, identifier les problèmes liés à vos configurations et prendre des mesures pour améliorer l'architecture des systèmes qui ne sont pas optimisés en termes de fiabilité, de sécurité, d'efficacité, de performances et de coût.

link:configuration-analysis.html["Découvrez l’analyse de configuration et l’état bien architecturé dans l’usine de charge de travail."]

.Description de la tâche
Workload Factory analyse quotidiennement les configurations de déploiement du système de fichiers Amazon FSx for NetApp ONTAP . Cette analyse quotidienne fournit un état d'avancement de l'architecture, des informations et des recommandations, ainsi que des options pour corriger automatiquement les problèmes de configuration afin que votre système de fichiers soit conforme aux meilleures pratiques.

Vous disposez d’options pour consulter les recommandations relatives aux problèmes de configuration de vos systèmes de fichiers et résoudre les problèmes à partir de l’inventaire de stockage dans la console de l’usine de charge de travail.

Ce qui est analysé:: Workload Factory analyse l'état bien conçu des configurations suivantes pour les systèmes de fichiers FSX pour ONTAP :
+
--
* Seuil de capacité SSD
* Tiering des données
* Snapshots locaux planifiés
* FSx pour les sauvegardes ONTAP
* Réplication des données à distance
* Fonctionnalités d'efficacité du stockage
* Gestion automatique de la capacité


--


.Avant de commencer
* Vous devez disposer d'informations d'identification avec des autorisations de _lecture seule_ ou de _lecture/écriture_. link:https://docs.netapp.com/us-en/workload-setup-admin/add-credentials.html["Découvrez comment octroyer des autorisations sur votre compte AWS"^].
* Vérifiez attentivement chaque recommandation avant de choisir de corriger un paramètre ou une configuration.



NOTE: Le processus de correction peut entraîner des temps d'indisponibilité d'instance ou des interruptions de service. Vérifiez attentivement la recommandation avant de choisir de résoudre un problème de configuration.

.Étapes
. Connectez-vous à l'aide de l'un des link:https://docs.netapp.com/us-en/workload-setup-admin/console-experiences.html["expériences de la console"^].
. Dans la mosaïque bases de données, sélectionnez *accéder à l'inventaire de stockage*.
. Dans l'onglet *FSX pour ONTAP*, naviguez jusqu'à la colonne *statut bien structuré* et sélectionnez les problèmes que le système de fichiers doit résoudre.
. Dans le tableau de bord bien conçu du système de fichiers, filtrez les problèmes de configuration par catégories, sous-catégories, état, gravité et balises.
. Sélectionnez la flèche déroulante pour afficher les recommandations pour une configuration. Assurez-vous de revoir attentivement la recommandation.
+
Cette recommandation présente les meilleures pratiques et les obstacles potentiels liés aux configurations non optimisées.

. Sélectionnez *fixer*.
+
Lorsque *View and fix* est une option, sélectionnez les volumes affectés à corriger.

. Passez en revue le résumé et les actions qui apparaissent dans la boîte de dialogue pour savoir ce qui se passera si vous choisissez de résoudre le problème. Certaines opérations peuvent entraîner des temps d'indisponibilité d'instance ou des interruptions de service.
. Sélectionnez *Continuer* pour résoudre le problème de configuration.


.Résultat
Le processus de résolution du problème démarre. Sélectionnez le menu des paramètres du compte, puis sélectionnez *Tracker* pour afficher l'état de l'opération.
