---
sidebar: sidebar 
permalink: increase-volume-capacity.html 
keywords: increase capacity, volume capacity 
summary: 'Augmentez manuellement à tout moment la capacité d"un volume en usine de workloads BlueXP .' 
---
= Augmentez la capacité de volume en usine de charges de travail BlueXP 
:allow-uri-read: 
:icons: font
:imagesdir: ./media/


[role="lead"]
Augmentez manuellement la capacité d'un volume à tout moment en usine de workloads BlueXP .

Vous pouvez également link:edit-volume-autogrow.html["activez la fonction de croissance automatique"]laisser l'usine de la charge de travail gérer la capacité du volume pour vous.

.Description de la tâche
Pour une LUN iSCSI, cette opération augmente la taille de la LUN hôte. Une fois la capacité augmentée, suivez la procédure fournie par votre système d'exploitation hôte pour découvrir la nouvelle taille de la LUN et développer le système de fichiers de la LUN.

.Avant de commencer
Pour augmenter la capacité du volume, vous devez associer un lien. link:https://docs.netapp.com/us-en/workload-fsx-ontap/create-link.html["Apprenez à associer un lien existant ou à créer et associer un nouveau lien"]. Une fois le lien associé, revenez à cette opération.

.Étapes
. Connectez-vous à l'aide de l'un des link:https://docs.netapp.com/us-en/workload-setup-admin/console-experiences.html["expériences de la console"^].
. Dans stockage, sélectionnez *accéder à l'inventaire de stockage*.
. Dans l'onglet *FSX pour ONTAP*, sélectionnez le menu à trois points du système de fichiers avec le volume à mettre à jour, puis sélectionnez *gérer*.
. Dans la présentation du système de fichiers, sélectionnez l'onglet *volumes*.
. Dans l'onglet volumes, sélectionnez le menu à trois points du volume pour augmenter la capacité de.
. Sélectionnez *actions de base*, puis *augmenter la capacité du volume*.
. Dans la boîte de dialogue augmenter la capacité du volume, indiquez les éléments suivants :
+
.. Sélectionnez une taille plus grande.
.. Remplacez l'unité si nécessaire.


. Sélectionnez *augmenter*.

