---
sidebar: sidebar 
permalink: increase-volume-capacity.html 
keywords: increase capacity, volume capacity 
summary: 'Augmentez manuellement la capacité d"un volume à tout moment.' 
---
= Augmentez la capacité du volume
:allow-uri-read: 
:icons: font
:imagesdir: ./media/


[role="lead"]
Augmentez manuellement la capacité d'un volume à tout moment.

Vous pouvez également link:edit-volume-autogrow.html["activez la fonction de croissance automatique"] laisser Workload Factory gérer la capacité du volume pour vous.

.Description de la tâche
Pour une LUN iSCSI, cette opération augmente la taille de la LUN hôte. Une fois la capacité augmentée, suivez la procédure fournie par votre système d'exploitation hôte pour découvrir la nouvelle taille de la LUN et développer le système de fichiers de la LUN.

.Avant de commencer
Pour augmenter la capacité du volume, vous devez link:manage-links.html["associer un lien"]. Si vous n'avez pas de lien existant, link:create-link.html["créer un lien"]. Pour associer un lien dans le système de fichiers, cliquez sur *lien associé* sous *Nom du compte*. Une fois le lien associé, revenez à cette opération.

.Étapes
. Connectez-vous au link:https://console.workloads.netapp.com/["Console Workload Factory"^]
. Dans stockage, sélectionnez *accéder à l'inventaire de stockage*.
. Dans l'onglet *FSX pour ONTAP*, sélectionnez le menu à trois points du système de fichiers avec le volume à mettre à jour, puis sélectionnez *gérer*.
. Dans la présentation du système de fichiers, sélectionnez l'onglet *volumes*.
. Dans l'onglet volumes, sélectionnez le menu à trois points du volume pour augmenter la capacité de.
. Sélectionnez *actions de base*, puis *augmenter la capacité du volume*.
. Dans la boîte de dialogue augmenter la capacité du volume, indiquez les éléments suivants :
+
.. Sélectionnez une taille plus grande.
.. Remplacez l'unité si nécessaire.


. Cliquez sur *augmenter*.

