---
sidebar: sidebar 
permalink: increase-volume-capacity.html 
keywords: increase capacity, volume capacity 
summary: Augmentez manuellement la capacité de volume d’un volume dans NetApp Workload Factory à tout moment. 
---
= Augmenter la capacité de volume dans NetApp Workload Factory
:allow-uri-read: 
:icons: font
:imagesdir: ./media/


[role="lead"]
Augmentez manuellement la capacité de volume d’un volume à tout moment dans NetApp Workload Factory.

En option, vous pouvezlink:edit-volume-autogrow.html["activez la fonction de croissance automatique"] pour laisser Workload Factory gérer la capacité du volume pour vous.

.Description de la tâche
Pour une LUN iSCSI, cette opération augmente la taille de la LUN hôte. Une fois la capacité augmentée, suivez la procédure fournie par votre système d'exploitation hôte pour découvrir la nouvelle taille de la LUN et développer le système de fichiers de la LUN.

.Avant de commencer
Pour augmenter la capacité du volume, vous devez associer un lien. link:https://docs.netapp.com/us-en/workload-fsx-ontap/create-link.html["Apprenez à associer un lien existant ou à créer et associer un nouveau lien"]. Une fois le lien associé, revenez à cette opération.

.Étapes
. Connectez-vous à l'aide de l'un des link:https://docs.netapp.com/us-en/workload-setup-admin/console-experiences.html["expériences de la console"^].
. Dans la mosaïque Stockage, sélectionnez *Accéder au stockage*.
. Dans le menu Stockage, sélectionnez *FSx pour ONTAP*.
. Depuis *FSx for ONTAP*, sélectionnez le menu d'actions du système de fichiers avec le volume à mettre à jour, puis sélectionnez *Gérer*.
. Dans la présentation du système de fichiers, sélectionnez l'onglet *volumes*.
. Dans l’onglet Volumes, sélectionnez le menu d’actions du volume pour lequel vous souhaitez augmenter la capacité.
. Sélectionnez *actions de base*, puis *augmenter la capacité du volume*.
. Dans la boîte de dialogue augmenter la capacité du volume, indiquez les éléments suivants :
+
.. Sélectionnez une taille plus grande.
.. Remplacez l'unité si nécessaire.


. Sélectionnez *Augmenter* pour appliquer la modification.

