---
sidebar: sidebar 
permalink: initialize-replication.html 
keywords: initialize replication, begin replication, start replication 
summary: Initialiser une relation de réplication entre les volumes source et cible 
---
= Initialiser une relation de réplication
:allow-uri-read: 
:icons: font
:imagesdir: ./media/


[role="lead"]
Initialiser une relation de réplication entre les volumes source et cible

.Description de la tâche
L'initialisation effectue un transfert _baseline_ : elle crée un instantané du volume source, puis transfère le snapshot et tous les blocs de données qu'il référence au volume cible.

.Avant de commencer
Tenez compte du moment où vous choisissez de terminer cette opération. L'initialisation peut prendre beaucoup de temps. Vous pouvez exécuter le transfert de base en dehors des heures creuses.

.Étapes
. Connectez-vous au link:https://console.workloads.netapp.com/["Console Workload Factory"^]
. Dans stockage, sélectionnez *accéder à l'inventaire de stockage*.
. Dans l'onglet *FSX pour ONTAP*, cliquez sur le menu à trois points du système de fichiers à mettre à jour, puis sélectionnez *gérer*.
. Dans la présentation du système de fichiers, sélectionnez l'onglet *relations de réplication*.
. Dans l'onglet Replication relations (relations de réplication), cliquez sur le menu des trois points de la relation de réplication à initialiser.
. Sélectionnez *initialiser*.
. Dans la boîte de dialogue Initialize relationship, cliquez sur *Initialize*.

