---
sidebar: sidebar 
permalink: initialize-replication.html 
keywords: initialize replication, begin replication, start replication 
summary: Initialiser une relation de réplication entre les volumes source et cible 
---
= Initialiser une relation de réplication dans NetApp Workload Factory
:allow-uri-read: 
:icons: font
:imagesdir: ./media/


[role="lead"]
Initialisez une relation de réplication entre les volumes source et cible pour transférer le snapshot et tous les blocs de données dans NetApp Workload Factory.

.Description de la tâche
L'initialisation effectue un transfert _baseline_ : elle crée un instantané du volume source, puis transfère le snapshot et tous les blocs de données qu'il référence au volume cible.

.Avant de commencer
Tenez compte du moment où vous choisissez de terminer cette opération. L'initialisation peut prendre beaucoup de temps. Vous pouvez exécuter le transfert de base en dehors des heures creuses.

.Étapes
. Connectez-vous à l'aide de l'un des link:https://docs.netapp.com/us-en/workload-setup-admin/console-experiences.html["expériences de la console"^].
. Dans la mosaïque Stockage, sélectionnez *Accéder au stockage*.
. Dans le menu Stockage, sélectionnez *FSx pour ONTAP*.
. Depuis *FSx for ONTAP*, sélectionnez le menu d'actions du système de fichiers à mettre à jour, puis sélectionnez *Gérer*.
. Dans la présentation du système de fichiers, sélectionnez l'onglet *relations de réplication*.
. Dans l’onglet Relations de réplication, sélectionnez le menu d’actions de la relation de réplication à initialiser.
. Sélectionnez *initialiser*.
. Dans la boîte de dialogue Initialize relationship, sélectionnez *Initialize*.

