---
sidebar: sidebar 
permalink: learn-fsx-ontap.html 
keywords: Amazon FSx for NetApp ONTAP, FSx, storage, aws 
summary: 'Amazon FSx for NetApp ONTAP est un service entièrement géré permettant aux clients de lancer et d"exécuter des systèmes de fichiers en tant que backend de stockage pour vos charges de travail dans Workload Factory.' 
---
= En savoir plus sur Amazon FSx for NetApp ONTAP dans NetApp Workload Factory
:allow-uri-read: 
:icons: font
:imagesdir: ./media/


[role="lead"]
Amazon FSx for NetApp ONTAP est un service de stockage de données entièrement géré et basé sur le cloud qui offre des capacités de gestion de données avancées et des performances hautement évolutives.  FSx for ONTAP vous permet de créer et de gérer des systèmes de fichiers en tant que backend de stockage pour toutes vos charges de travail dans NetApp Workload Factory.

FSX pour ONTAP offre les mêmes fonctionnalités, performances et administration que les clients NetApp utilisent l'environnement sur site, avec la simplicité, l'agilité, la sécurité et l'évolutivité d'un service AWS natif.

FSx pour ONTAP est le composant _Storage_ de Workload Factory.



== Caractéristiques

FSX pour ONTAP offre les fonctionnalités suivantes :

* *Service entièrement géré* : fournit un service entièrement géré intégré à la console Workload Factory.
* *Haute disponibilité* : fournit une haute disponibilité pour chaque système de fichiers FSX for ONTAP, prenant en charge les déploiements à zones de disponibilité unique et multiple.
* *Instantanés automatisés* : protège les données à l'aide de snapshots automatisés et efficaces, qui sont des copies ponctuelles quasi instantanées et compactes du ou des volumes de système de fichiers en lecture seule.
* *Réplication de volume* : fournit une reprise après incident avec réplication interrégionale sur Amazon Web Services.
* *Sauvegardes efficaces* : ajoute une couche supplémentaire de protection avec une copie des données dans une autre région pour les urgences.
* *Clonage rapide* : accélère le développement des applications grâce au clonage rapide.
* *Prise en charge multiprotocole* : prend en charge les protocoles NFS (Network File System), SMB (Server message Block) et iSCSI (Internet Small Computer Systems interface).
* *Débit élevé* : fournit des performances de débit élevées pour garantir des latences faibles aux charges de travail exécutées sur les systèmes de fichiers FSX for ONTAP.
* *Cache in-memory et NVMe cache* : inclut un cache in-memory unique et un cache NVMe qui améliore les performances des données fréquemment utilisées.
* *Des centaines de milliers d'IOPS* : fournit des centaines de milliers d'IOPS avec des disques SSD, garantissant ainsi des résultats rapides pour votre stockage et vos charges de travail.
* *Provisionnement fin* : permet le provisionnement de capacité à l'avance, ce qui permet d'économiser des coûts jusqu'à ce que de la capacité supplémentaire soit nécessaire.
* *La déduplication et la compression des données* : supprime les données dupliquées et compresse les données pour réduire la quantité de stockage physique requise pour les systèmes de fichiers FSX for ONTAP, ce qui permet de réaliser des économies.
* *Tiering des données* : permet de réduire les coûts de stockage en déplaçant les données les moins fréquemment utilisées du niveau de stockage SSD haute performance principal vers le niveau de stockage du pool de capacité secondaire.




== Fonctionnalités supplémentaires dans Workload Factory

* *Calculateur de comparaison des coûts de stockage* : compare les coûts de stockage d'Amazon Elastic Block Store (EBS), d'Elastic File System (EFS) et de FSX for Windows File Server avec FSX for ONTAP. À partir du calculateur, vous pouvez voir comment les configurations de stockage FSX pour ONTAP permettent de réaliser des économies et de planifier votre transition vers FSX pour le stockage ONTAP.
* *Interface utilisateur de Workload Factory* : fournit les options de mode de création rapide_ et de déploiement _Advanced create_. La création rapide inclut AWS, NetApp et les bonnes pratiques standard pour vos configurations de stockage.
* *Codebox* : fournit aux développeurs un visualiseur de code pour les opérations FSX for ONTAP, des modèles de code pour la copie et le téléchargement, et un catalogue d'automatisation pour la réutilisation du code.




== Outils pour utiliser NetApp Workload Factory

Vous pouvez utiliser NetApp Workload Factory avec les outils suivants :

* *Console Workload Factory* : La console Workload Factory fournit une vue visuelle et holistique de vos applications et projets.
* * Console NetApp * : la console NetApp fournit une expérience d'interface hybride afin que vous puissiez utiliser Workload Factory avec d'autres services de données NetApp .
* *Demandez-moi* : utilisez l'assistant IA Ask me pour poser des questions et en savoir plus sur Workload Factory sans quitter la console Workload Factory. Accédez à Demandez-moi depuis le menu d'aide de Workload Factory.
* *CloudShell CLI* : Workload Factory inclut une CLI CloudShell pour gérer et exploiter les environnements AWS et NetApp sur plusieurs comptes à partir d'une seule CLI basée sur un navigateur. Accédez à CloudShell depuis la barre supérieure de la console Workload Factory.
* *API REST* : utilisez les API REST de Workload Factory pour déployer et gérer vos systèmes de fichiers FSx for ONTAP et d'autres ressources AWS.
* *CloudFormation* : utilisez le code AWS CloudFormation pour effectuer les actions que vous avez définies dans la console Workload Factory afin de modéliser, provisionner et gérer les ressources AWS et tierces de la pile CloudFormation dans votre compte AWS.
* *Fournisseur Terraform NetApp Workload Factory* : utilisez Terraform pour créer et gérer les workflows d'infrastructure générés dans la console Workload Factory.




== Le coût

AWS gère votre compte FSx pour ONTAP , pas Workload Factory. link:https://docs.aws.amazon.com/fsx/latest/ONTAPGuide/what-is-fsx-ontap.html#pricing-for-fsx-ontap["Tarifs pour Amazon FSX for NetApp ONTAP"^] .



== Régions

Workload Factory est pris en charge dans toutes les régions commerciales où FSx for ONTAP est pris en charge.link:https://aws.amazon.com/about-aws/global-infrastructure/regional-product-services/["Affichez les régions Amazon prises en charge."^]

Les régions AWS suivantes ne sont pas prises en charge :

* régions de Chine
* Régions GovCloud (États-Unis)
* Nuage secret
* Nuage top secret




== Obtenir de l'aide

Amazon FSX pour NetApp ONTAP est une solution propriétaire AWS. Pour toute question ou tout problème de support technique associé à votre système de fichiers FSX for ONTAP, à votre infrastructure ou à toute solution utilisant ce service, utilisez le centre de support de votre console de gestion AWS pour ouvrir un dossier de support avec AWS. Sélectionnez le service “FSX pour ONTAP” et la catégorie appropriée. Fournissez les informations restantes nécessaires pour créer un dossier de demande de support AWS.

Pour des questions générales sur Workload Factory ou les applications et services Workload Factory, reportez-vous àlink:get-help.html["Obtenez de l'aide pour FSx pour ONTAP pour Workload Factory"] .
