---
sidebar: sidebar 
permalink: learn-fsx-ontap.html 
keywords: Amazon FSx for NetApp ONTAP, FSx, storage, aws 
summary: 'Amazon FSX pour NetApp ONTAP est un service entièrement géré qui permet aux clients de lancer et d"exécuter des systèmes de fichiers en tant que système back-end de stockage pour vos workloads dans l"usine de workloads.' 
---
= Découvrez Amazon FSX pour NetApp ONTAP dans l'usine de workloads BlueXP 
:allow-uri-read: 
:icons: font
:imagesdir: ./media/


[role="lead"]
Amazon FSX pour NetApp ONTAP est un service de stockage des données cloud entièrement géré qui offre des capacités avancées de gestion des données et des performances hautement évolutives. FSX pour ONTAP vous permet de créer et de gérer des systèmes de fichiers en tant que système back-end de stockage pour tous vos workloads dans l'usine de workloads BlueXP .

FSX pour ONTAP offre les mêmes fonctionnalités, performances et administration que les clients NetApp utilisent l'environnement sur site, avec la simplicité, l'agilité, la sécurité et l'évolutivité d'un service AWS natif.

FSX for ONTAP est le composant _stockage_ en usine de la charge de travail.



== Caractéristiques

FSX pour ONTAP offre les fonctionnalités suivantes :

* *Service entièrement géré* : fournit un service entièrement géré intégré à la console d'usine de la charge de travail.
* *Haute disponibilité* : fournit une haute disponibilité pour chaque système de fichiers FSX for ONTAP, prenant en charge les déploiements à zones de disponibilité unique et multiple.
* *Instantanés automatisés* : protège les données à l'aide de snapshots automatisés et efficaces, qui sont des copies ponctuelles quasi instantanées et compactes du ou des volumes de système de fichiers en lecture seule.
* *Réplication de volume* : fournit une reprise après incident avec réplication interrégionale sur Amazon Web Services.
* *Sauvegardes efficaces* : ajoute une couche supplémentaire de protection avec une copie des données dans une autre région pour les urgences.
* *Clonage rapide* : accélère le développement des applications grâce au clonage rapide.
* *Prise en charge multiprotocole* : prend en charge les protocoles NFS (Network File System), SMB (Server message Block) et iSCSI (Internet Small Computer Systems interface).
* *Débit élevé* : fournit des performances de débit élevées pour garantir des latences faibles aux charges de travail exécutées sur les systèmes de fichiers FSX for ONTAP.
* *Cache in-memory et NVMe cache* : inclut un cache in-memory unique et un cache NVMe qui améliore les performances des données fréquemment utilisées.
* *Des centaines de milliers d'IOPS* : fournit des centaines de milliers d'IOPS avec des disques SSD, garantissant ainsi des résultats rapides pour votre stockage et vos charges de travail.
* *Provisionnement fin* : permet le provisionnement de capacité à l'avance, ce qui permet d'économiser des coûts jusqu'à ce que de la capacité supplémentaire soit nécessaire.
* *La déduplication et la compression des données* : supprime les données dupliquées et compresse les données pour réduire la quantité de stockage physique requise pour les systèmes de fichiers FSX for ONTAP, ce qui permet de réaliser des économies.
* *Tiering des données* : permet de réduire les coûts de stockage en déplaçant les données les moins fréquemment utilisées du niveau de stockage SSD haute performance principal vers le niveau de stockage du pool de capacité secondaire.




== Fonctions supplémentaires en usine pour les charges de travail

* *Calculateur de comparaison des coûts de stockage* : compare les coûts de stockage d'Amazon Elastic Block Store (EBS), d'Elastic File System (EFS) et de FSX for Windows File Server avec FSX for ONTAP. À partir du calculateur, vous pouvez voir comment les configurations de stockage FSX pour ONTAP permettent de réaliser des économies et de planifier votre transition vers FSX pour le stockage ONTAP.
* *Interface utilisateur de Workload Factory* : fournit les options de mode de création rapide_ et de déploiement _Advanced create_. La création rapide inclut AWS, NetApp et les bonnes pratiques standard pour vos configurations de stockage.
* *Codebox* : fournit aux développeurs un visualiseur de code pour les opérations FSX for ONTAP, des modèles de code pour la copie et le téléchargement, et un catalogue d'automatisation pour la réutilisation du code.




== Outils pour utiliser l'usine de charge de travail

Vous pouvez utiliser l'usine de workloads BlueXP  avec les outils suivants :

* *Workload Factory console*: La console de fabrique de charge de travail offre une vue visuelle et holistique de vos applications et projets.
* *Console BlueXP * : la console BlueXP  offre une interface hybride pour que vous puissiez utiliser la fabrique de workloads BlueXP  avec d'autres services BlueXP .
* *Posez-moi* : utilisez l'assistant Ask Me ai pour poser des questions et en savoir plus sur l'usine de charge de travail sans quitter l'interface utilisateur Web de l'usine de charge de travail. Accédez à Me demander à partir du menu d'aide de l'usine de la charge de travail.
* *CLI CloudShell* : la fabrique de workloads inclut une interface de ligne de commande CloudShell pour gérer et exploiter les environnements AWS et NetApp entre les comptes à partir d'une seule interface de ligne de commande basée sur navigateur. Accédez à CloudShell à partir de la barre supérieure de la console d'usine de la charge de travail.
* *API REST* : utilisez les API REST d'usine pour déployer et gérer vos systèmes de fichiers FSX pour ONTAP et d'autres ressources AWS.
* *CloudFormation* : utilisez le code AWS CloudFormation pour effectuer les actions que vous avez définies dans la console d'usine de la charge de travail afin de modéliser, de provisionner et de gérer les ressources AWS et tierces à partir de la pile CloudFormation de votre compte AWS.
* *Terraform BlueXP  Workload Factory Provider* : utilisez Terraform pour créer et gérer les flux de travail d'infrastructure générés dans la console d'usine de la charge de travail.




== Le coût

AWS maintient votre compte FSX pour ONTAP, pas l'usine de workloads. Reportez-vous à la link:https://docs.aws.amazon.com/fsx/latest/ONTAPGuide/what-is-fsx-ontap.html#pricing-for-fsx-ontap["Tarifs pour Amazon FSX for NetApp ONTAP"^].



== Régions prises en charge

https://aws.amazon.com/about-aws/global-infrastructure/regional-product-services/["Affichez les régions Amazon prises en charge."^]



== Obtenir de l'aide

Amazon FSX pour NetApp ONTAP est une solution propriétaire AWS. Pour toute question ou tout problème de support technique associé à votre système de fichiers FSX for ONTAP, à votre infrastructure ou à toute solution utilisant ce service, utilisez le centre de support de votre console de gestion AWS pour ouvrir un dossier de support avec AWS. Sélectionnez le service “FSX pour ONTAP” et la catégorie appropriée. Fournissez les informations restantes nécessaires pour créer un dossier de demande de support AWS.

Pour des questions d'ordre général sur les applications et services d'usine de charge de travail ou d'usine, reportez-vous à link:get-help.html["Obtenez de l'aide sur FSX pour ONTAP pour l'usine de workloads"].
