---
sidebar: sidebar 
permalink: limit-transfer-rate.html 
keywords: limit max transfer rate, limit transfer rate 
summary: 'Limitez le taux de transfert maximal d"une relation de réplication en usine de workloads BlueXP .' 
---
= Limitez le taux de transfert maximal d'une relation de réplication
:allow-uri-read: 
:icons: font
:imagesdir: ./media/


[role="lead"]
Limitez le taux de transfert maximal d'une relation de réplication en usine de workloads BlueXP . Un taux de transfert illimité peut avoir un impact négatif sur les performances d'autres applications et de votre réseau.

.Description de la tâche
La limitation du taux de transfert maximal est facultative, mais recommandée. Sans limite, les performances du réseau et des applications peuvent diminuer.

Nous recommandons également un taux de transfert illimité pour les systèmes de fichiers FSX pour ONTAP pour les workloads stratégiques, par exemple ceux utilisés principalement pour la reprise d'activité.

.Avant de commencer
Tenez compte de la quantité de bande passante à allouer à la réplication.

.Étapes
. Connectez-vous à l'aide de l'un des link:https://docs.netapp.com/us-en/workload-setup-admin/console-experiences.html["expériences de la console"^].
. Dans stockage, sélectionnez *accéder à l'inventaire de stockage*.
. Dans l'onglet *FSX pour ONTAP*, sélectionnez le menu à trois points du système de fichiers à mettre à jour, puis sélectionnez *gérer*.
. Dans la présentation du système de fichiers, sélectionnez l'onglet *relations de réplication*.
. Dans l'onglet relations de réplication, sélectionnez le menu à trois points de la relation de réplication pour limiter le taux de transfert maximal pour.
. Sélectionnez *Modifier le taux de transfert max*.
. Dans la boîte de dialogue Modifier le taux de transfert maximal, sélectionnez *limité* et entrez la limite de transfert maximale en Mo/s.
+
Vous pouvez également sélectionner *Illimité*.

. Sélectionnez *appliquer*.

