---
sidebar: sidebar 
permalink: links-overview.html 
keywords: links, accounts, lambda 
summary: Un lien Workload Factory crée une relation de confiance et une connectivité entre un compte Workload Factory et un ou plusieurs systèmes de fichiers FSX for ONTAP. Vous pouvez ainsi contrôler et gérer certaines fonctionnalités du système de fichiers directement à partir des API REST ONTAP qui ne sont pas disponibles via les API Amazon FSX pour ONTAP. 
---
= Cliquez ici pour en savoir plus sur les liens Workload Factory
:allow-uri-read: 
:icons: font
:imagesdir: ./media/


[role="lead"]
Un lien Workload Factory crée une relation de confiance et une connectivité entre un compte Workload Factory et un ou plusieurs systèmes de fichiers FSX for ONTAP. Vous pouvez ainsi surveiller et gérer certaines fonctionnalités du système de fichiers directement à partir des appels de l'API REST ONTAP qui ne sont pas disponibles via l'API Amazon FSX pour ONTAP.

Vous n'avez pas besoin d'un lien pour commencer à utiliser Workload Factory, mais dans certains cas, vous devrez créer un lien pour déverrouiller toutes les fonctionnalités de Workload Factory et de charge de travail.



== Fonctionnement des liens

Les liens utilisent AWS Lambda. Lambda exécute le code en réponse aux événements et gère automatiquement les ressources informatiques requises par ce code. Les liens que vous créez font partie de votre compte NetApp et sont associés à un compte AWS.

Après avoir créé un lien, vous pouvez l'associer à un ou plusieurs systèmes de fichiers FSX pour ONTAP. Chaque système de fichiers ne peut être associé qu'à un seul lien dans le même compte NetApp. Si vous avez plusieurs comptes NetApp, un seul système de fichiers peut être associé à des liens supplémentaires sous différents comptes NetApp.

Vous créez des liens à partir des pages du système de fichiers FSX pour ONTAP dans Workload Factory. link:create-link.html["Découvrez comment créer des liens"] pour plus d'informations.



== Coûts

Chaque transaction effectuée par Lambda entraîne des frais. Lambda agissant comme proxy entre les deux systèmes, Lambda envoie une requête à l'API REST de ONTAP sur un système de fichiers et renvoie la réponse à Workload Factory.

link:https://aws.amazon.com/lambda/pricing/["Découvrez les coûts liés à l'utilisation d'AWS Lambda"^]



== Lorsqu'un lien est requis

Workload Factory nécessite un lien pour afficher certaines informations et effectuer certaines tâches. Si vous tentez d'effectuer une opération qui nécessite un lien et que vous n'avez pas associé de lien au système de fichiers FSX pour ONTAP, un message vous indique que l'opération nécessite un lien. Vous pouvez ajouter un nouveau lien ou associer le système de fichiers FSX pour ONTAP à un lien existant à ce moment-là afin de pouvoir exécuter l'opération.

Les fonctions qui nécessitent un lien sont les suivantes :

* Affiche la version de ONTAP installée sur un système de fichiers FSX pour ONTAP
* Gérer les volumes iSCSI sur le système
* Activer et désactiver la fonction de croissance automatique pour les volumes
* Création et gestion de règles de snapshots
* Configurez les relations de réplication et répliquez les volumes entre les systèmes de fichiers
* Configurez les relations de sauvegarde et sauvegardez les données de volume dans le stockage cloud
* Cloner des volumes dans un système de fichiers
* Affichage des metrics supplémentaires directement à partir de ONTAP (les metrics par défaut sont collectées par Amazon CloudWatch)
* Gestion des règles d'exportation NFS

