---
sidebar: sidebar 
permalink: manage-cifs-share.html 
keywords: cifs, smb, SMB/CIFS, cifs share, change, update, modify, delete, create 
summary: 'La gestion du partage SMB/CIFS d"un volume dans Workload Factory inclut la création, la détermination de l"accès des utilisateurs et des groupes, ainsi que la suppression.' 
---
= Gérer le partage SMB/CIFS pour un volume dans Workload Factory
:allow-uri-read: 
:icons: font
:imagesdir: ./media/


[role="lead"]
La gestion du partage SMB/CIFS d'un volume dans Workload Factory inclut la création du partage SMB/CIFS, la détermination des utilisateurs et des groupes auxquels accorder l'accès et le niveau d'autorisations à leur accorder, ainsi que la suppression du partage SMB/CIFS.

.Avant de commencer
Avant de commencer, procédez comme suit :

* Pour gérer les partages SMB/CIFS, vous devez associer un lien. link:https://docs.netapp.com/us-en/workload-fsx-ontap/create-link.html["Apprenez à associer un lien existant ou à créer et associer un nouveau lien"] .  Une fois le lien associé, revenez à cette opération.
* Déterminez les utilisateurs ou les groupes auxquels accorder l'accès et le niveau d'autorisation à leur accorder.




== Créer un partage SMB/CIFS pour un volume

Suivez les étapes pour créer un partage SMB/CIFS pour un volume.

.Étapes
. Connectez-vous à l'aide de l'un des link:https://docs.netapp.com/us-en/workload-setup-admin/console-experiences.html["expériences de la console"^].
. Dans la mosaïque Stockage, sélectionnez *Accéder au stockage*.
. Dans le menu Stockage, sélectionnez *FSx pour ONTAP*.
. Depuis *FSx for ONTAP*, sélectionnez le menu d'actions du système de fichiers avec le volume à mettre à jour, puis sélectionnez *Gérer*.
. Dans la présentation du système de fichiers, sélectionnez l'onglet *volumes*.
. Dans l’onglet Volumes, sélectionnez le menu d’actions du volume pour lequel modifier le partage SMB.
. Sélectionnez *Actions avancées*, puis *Gérer les partages SMB/CIFS*.
. Sur la page Gérer les partages SMB/CIFS, sélectionnez *Créer un partage SMB/CIFS*.
. Dans la boîte de dialogue Créer un partage SMB/CIFS, fournissez les éléments suivants :
+
.. *Nom* : saisissez le nom du partage SMB/CIFS.
.. *Chemin* : définissez le chemin en utilisant le nom de volume par défaut ou fournissez un partage vers un répertoire interne.
+
Les entrées de chemin valides pour le nom du volume, par exemple « avocat », sont les suivantes :

+
*** /avocat
*** /avocat/dossier
*** /avocat/dossier/sous-dossier
*** /avocat/nom-de-fichier
+
Les entrées de chemin valides pour le nom de partage, par exemple « Serveur », sont les suivantes :

*** \\Serveur
*** \\Serveur\Projets
*** \\Serveur\Projets\Ressources partagées


.. *Autorisations* : sélectionnez contrôle total, lecture/écriture, lecture ou aucun accès, puis entrez les utilisateurs ou les groupes séparés par un point-virgule ( ; ). Les utilisateurs ou les groupes sont sensibles à la casse et le domaine de l'utilisateur doit être inclus au format « domaine\nom d'utilisateur ».


. Sélectionnez *Créer*.




== Modifier un partage SMB/CIFS pour un volume

Suivez les étapes pour modifier les paramètres de partage SMB/CIFS pour un volume.

.Étapes
. Connectez-vous à l'aide de l'un des link:https://docs.netapp.com/us-en/workload-setup-admin/console-experiences.html["expériences de la console"^].
. Dans la mosaïque Stockage, sélectionnez *Accéder au stockage*.
. Dans l'onglet *FSx for ONTAP*, sélectionnez le menu d'actions du système de fichiers avec le volume à mettre à jour, puis sélectionnez *Gérer*.
. Dans la présentation du système de fichiers, sélectionnez l'onglet *volumes*.
. Dans l’onglet Volumes, sélectionnez le menu d’actions du volume pour lequel modifier le partage SMB.
. Sélectionnez *Actions avancées*, puis *Gérer les partages SMB/CIFS*.
. Sur la page Gérer les partages SMB/CIFS, sélectionnez *Afficher et modifier*.
. Modifiez les autorisations d’accès SMB/CIFS, ou les utilisateurs ou groupes auxquels accorder des autorisations.
+
Les modifications peuvent entraîner la perte de l’accès des utilisateurs ou des groupes actuels au partage SMB/CIFS.

. Sélectionnez *appliquer* pour enregistrer les modifications.




== Supprimer un partage SMB/CIFS pour un volume

Suivez les étapes pour supprimer un partage SMB/CIFS pour un volume.

.Étapes
. Connectez-vous à l'aide de l'un des link:https://docs.netapp.com/us-en/workload-setup-admin/console-experiences.html["expériences de la console"^].
. Dans la mosaïque Stockage, sélectionnez *Accéder au stockage*.
. Dans l'onglet *FSx for ONTAP*, sélectionnez le menu d'actions du système de fichiers avec le volume à mettre à jour, puis sélectionnez *Gérer*.
. Dans la présentation du système de fichiers, sélectionnez l'onglet *volumes*.
. Dans l’onglet Volumes, sélectionnez le menu d’actions du volume pour lequel modifier le partage SMB.
. Sélectionnez *Actions avancées*, puis *Gérer les partages SMB/CIFS*.
. Sur la page Gérer les partages SMB/CIFS, sélectionnez le menu d'actions du partage SMB/CIFS, puis sélectionnez *Supprimer*.
+
La suppression du partage SMB/CIFS le rend indisponible et inaccessible à tout utilisateur souhaitant le monter.

. Dans la boîte de dialogue Supprimer le partage SMB/CIFS, sélectionnez *Supprimer* pour confirmer la suppression.

