---
sidebar: sidebar 
permalink: manage-volume-tags.html 
keywords: volume tags, edit volume tags, edit tags 
summary: Les balises peuvent vous aider à classer vos ressources. Vous pouvez ajouter, modifier et supprimer des balises de volume à tout moment pour les volumes FSX for ONTAP. 
---
= Gérer les balises de volume dans NetApp Workload Factory
:allow-uri-read: 
:icons: font
:imagesdir: ./media/


[role="lead"]
Les balises peuvent vous aider à catégoriser vos ressources.  Vous pouvez ajouter, modifier et supprimer des balises de volume à tout moment pour les volumes FSx for ONTAP dans NetApp Workload Factory.

.Étapes
. Connectez-vous à l'aide de l'un des link:https://docs.netapp.com/us-en/workload-setup-admin/console-experiences.html["expériences de la console"^].
. Dans la mosaïque Stockage, sélectionnez *Accéder au stockage*.
. Dans le menu Stockage, sélectionnez *FSx pour ONTAP*.
. Depuis *FSx for ONTAP*, sélectionnez le menu d'actions du système de fichiers avec le volume à mettre à jour, puis sélectionnez *Gérer*.
. Dans la présentation du système de fichiers, sélectionnez l'onglet *volumes*.
. Dans l’onglet Volumes, sélectionnez le menu d’actions du volume pour lequel modifier les balises.
. Sélectionnez *actions de base* puis *Modifier les balises de volume*.
. Sur la page Modifier les balises de volume, ajoutez, modifiez ou supprimez des balises.
+
Le nombre maximum de balises que vous pouvez appliquer à un volume est de 50.

. Sélectionnez *appliquer*.

