---
sidebar: sidebar 
permalink: manage-nfs-export-policy.html 
keywords: NFS, nfs, export policy, change export policy, update export policy, modify export policy 
summary: 'Gérez la export policy NFS pour un volume qui utilise les types de protocole NFSv3 ou NFSv4.1 dans l"usine de charges de travail BlueXP .' 
---
= Gérez la export policy NFS pour un volume en usine de workloads BlueXP 
:allow-uri-read: 
:icons: font
:imagesdir: ./media/


[role="lead"]
Gérez la export policy NFS pour un volume qui utilise les types de protocole NFSv3 ou NFSv4.1 dans l'usine de charges de travail BlueXP .

.Description de la tâche
La gestion des règles d'export d'un volume implique l'ajout de règles d'export détaillant les spécifications client, le contrôle d'accès, l'accès super-utilisateur et la version NFS. Vous pouvez ajouter plusieurs export-policy et les hiérarchisez.

.Avant de commencer
Déterminez les spécifications client pour les règles d'export-policy. Les valeurs valides pour la spécification client sont les suivantes :

* Adresses IP
* Adresses IP avec masques de sous-réseau
* Adresses IP avec un masque de réseau
* Un nom de groupe réseau précédé du caractère “@”
* Un nom de domaine précédé d'un point « ».
* Noms d'hôte


.Étapes
. Connectez-vous à l'aide de l'un des link:https://docs.netapp.com/us-en/workload-setup-admin/console-experiences.html["expériences de la console"^].
. Dans stockage, sélectionnez *accéder à l'inventaire de stockage*.
. Dans l'onglet *FSX pour ONTAP*, sélectionnez le menu à trois points du système de fichiers avec le volume à mettre à jour, puis sélectionnez *gérer*.
. Dans la présentation du système de fichiers, sélectionnez l'onglet *volumes*.
. Dans l'onglet volumes, sélectionnez le menu à trois points du volume pour lequel vous souhaitez modifier la règle d'export NFS.
. Sélectionnez *actions avancées*, puis *Modifier la règle d'export NFS*.
. Sur la page Modifier les règles d'export NFS, fournissez les informations suivantes :
+
.. *Contrôle d'accès* : sélectionnez *règle d'export personnalisée* ou *règle d'export existante*.
+
Vous pouvez également sélectionner *pas d'accès au volume*.

.. *Export policy name* : vous pouvez éventuellement entrer un nom pour la export policy.
.. *Ajouter une règle de stratégie d'exportation* : fournissez les détails suivants et classez les stratégies en commençant par #1 comme règle de priorité :
+
... *Spécification client* : séparez les valeurs multiples par des virgules.
... *Contrôle d'accès* : sélectionnez *lecture/écriture*, *lecture seule* ou *pas d'accès* dans le menu déroulant.
... *Super accès utilisateur* : sélectionnez *Oui* ou *non*.
... *Version NFS* : sélectionnez *All*, *NFSv3* ou *NFSv4*.




. Sélectionnez *appliquer*.

