---
sidebar: sidebar 
permalink: manage-volume-tags.html 
keywords: volume tags, edit volume tags, edit tags 
summary: Les balises peuvent vous aider à classer vos ressources. Vous pouvez ajouter, modifier et supprimer des balises de volume à tout moment pour les volumes FSX for ONTAP. 
---
= Gérez les balises de volume en usine de workloads BlueXP 
:allow-uri-read: 
:icons: font
:imagesdir: ./media/


[role="lead"]
Les balises peuvent vous aider à classer vos ressources. Vous pouvez ajouter, modifier et supprimer des balises de volume à tout moment pour les volumes FSX for ONTAP en usine de workloads BlueXP .

.Étapes
. Connectez-vous à l'aide de l'un des link:https://docs.netapp.com/us-en/workload-setup-admin/console-experiences.html["expériences de la console"^].
. Dans stockage, sélectionnez *accéder à l'inventaire de stockage*.
. Dans l'onglet *FSX pour ONTAP*, sélectionnez le menu à trois points du système de fichiers avec le volume à mettre à jour, puis sélectionnez *gérer*.
. Dans la présentation du système de fichiers, sélectionnez l'onglet *volumes*.
. Dans l'onglet volumes, sélectionnez le menu à trois points du volume pour lequel modifier les balises.
. Sélectionnez *actions de base* puis *Modifier les balises de volume*.
. Sur la page Modifier les balises de volume, ajoutez, modifiez ou supprimez des balises.
+
Le nombre maximum de balises que vous pouvez appliquer à un volume est de 50.

. Sélectionnez *appliquer*.

