---
sidebar: sidebar 
permalink: manage-snapshot-policy.html 
keywords: manage snapshot policy, change snapshot policy, snapshot policies, snapshot schedule, update 
summary: Gérez les stratégies de snapshot pour les volumes FSx for ONTAP dans Workload Factory.  Une politique de snapshot définit la manière dont le système crée des snapshots pour un volume. 
---
= Gérer les règles relatives aux snapshots
:allow-uri-read: 
:icons: font
:imagesdir: ./media/


[role="lead"]
Gérez les stratégies de snapshot pour les volumes FSx for ONTAP dans Workload Factory.  Une politique de snapshot définit la manière dont le système crée des snapshots pour un volume.

.Description de la tâche
Les opérations de gestion des snapshots, telles que l'attribution, la modification et la suppression de règles de snapshots pour les volumes d'un système de fichiers FSX pour ONTAP, sont gérées au niveau des machines virtuelles de stockage. Les règles Snapshot peuvent être partagées avec une seule VM de stockage ou avec toutes les VM de stockage.

Certaines tâches de gestion nécessitent d’associer un lien au système de fichiers FSx for ONTAP . link:https://docs.netapp.com/us-en/workload-fsx-ontap/links-overview.html["En savoir plus sur les liens Workload Factory"] .

Par défaut, chaque volume est associé à la règle de snapshot du système de fichiers `default` . Il est recommandé d'utiliser cette règle pour la plupart des workloads.



== Modifier une règle de snapshot

Vous pouvez modifier le nom de la stratégie de snapshots, la planification et le nombre de copies à conserver, et activer ou désactiver les snapshots immuables. Il n'est pas possible d'activer ou de désactiver le partage de règles entre les machines virtuelles de stockage. Cette option n'est disponible que lors de la création de la règle de snapshots.

.Avant de commencer
Pour afficher les stratégies d’instantané existantes, vous devez associer un lien. link:https://docs.netapp.com/us-en/workload-fsx-ontap/create-link.html["Apprenez à associer un lien existant ou à créer et associer un nouveau lien"]. Une fois le lien associé, revenez à cette opération.

.Étapes
. Connectez-vous à l'aide de l'un des link:https://docs.netapp.com/us-en/workload-setup-admin/console-experiences.html["expériences de la console"^].
. Dans *Stockage*, sélectionnez *Accéder au stockage*.
. Dans l'onglet *FSx for ONTAP*, sélectionnez le menu actions du système de fichiers, puis sélectionnez *Gérer*.
. Dans la présentation du système de fichiers, sélectionnez l'onglet *Storage VMS*.
. Dans l'onglet *VM de stockage*, sélectionnez le menu d'actions pour la machine virtuelle de stockage contenant le volume à protéger avec des snapshots planifiés, puis *Actions avancées*, puis *Gérer les stratégies de snapshot*.
. Sur la page de gestion des stratégies d'instantané, sélectionnez le menu d'actions pour la stratégie d'instantané à modifier, puis sélectionnez *Modifier*.
. Dans la boîte de dialogue Modifier la stratégie de snapshot, apportez les modifications nécessaires à la stratégie de snapshot.
. Sélectionnez *appliquer*.


.Résultat
La politique Snapshot est mise à jour.



== Assurez la mise en œuvre de snapshots immuables

Verrouiller les snapshots pour les empêcher d'être supprimés pendant la période de conservation.

.Avant de commencer
Vous devez associer un lien pour activer les instantanés immuables. link:https://docs.netapp.com/us-en/workload-fsx-ontap/create-link.html["Apprenez à associer un lien existant ou à créer et associer un nouveau lien"]. Une fois le lien associé, revenez à cette opération.

.Étapes
. Connectez-vous à l'aide de l'un des link:https://docs.netapp.com/us-en/workload-setup-admin/console-experiences.html["expériences de la console"^].
. Dans *Stockage*, sélectionnez *Accéder au stockage*.
. Dans l'onglet *FSx pour ONTAP*, sélectionnez le menu d'actions du système de fichiers qui contient le volume pour lequel verrouiller les instantanés, puis sélectionnez *Gérer*.
. Dans la présentation du système de fichiers, sélectionnez l'onglet *volumes*.
. Dans l’onglet *Volumes*, sélectionnez le menu d’actions du volume à protéger.
. Sélectionnez *actions de protection des données*, *instantanés*, puis *rendre un instantané immuable*.
. Dans la boîte de dialogue rendre un instantané immuable, procédez comme suit :
+
.. *Nom de l'instantané* : sélectionnez l'instantané à verrouiller.
.. Définissez la *période de conservation* en nombre d'heures, de jours, de mois ou d'années.
.. Acceptez la déclaration.


. Sélectionnez *appliquer*.


.Résultat
L'instantané du volume est maintenant verrouillé.



== Affecter une politique de snapshots à un volume

Vous pouvez affecter une politique de snapshots à un seul volume pour créer des snapshots planifiés pour ce volume.

.Avant de commencer
Vous devez associer un lien pour attribuer une politique de snapshot. link:https://docs.netapp.com/us-en/workload-fsx-ontap/create-link.html["Apprenez à associer un lien existant ou à créer et associer un nouveau lien"]. Une fois le lien associé, revenez à cette opération.

.Étapes
. Connectez-vous à l'aide de l'un des link:https://docs.netapp.com/us-en/workload-setup-admin/console-experiences.html["expériences de la console"^].
. Dans *Stockage*, sélectionnez *Accéder au stockage*.
. Dans l'onglet *FSx pour ONTAP*, sélectionnez le menu d'actions du système de fichiers contenant le volume auquel attribuer une stratégie de snapshot, puis sélectionnez *Gérer*.
. Dans la présentation du système de fichiers, sélectionnez l'onglet *Storage VMS*.
. Dans l'onglet *VM de stockage*, sélectionnez le menu d'actions pour la machine virtuelle de stockage contenant le volume à protéger avec des snapshots planifiés, puis *Actions avancées*, puis *Gérer les stratégies de snapshot*.
. Sur la page de gestion des stratégies d'instantanés, sélectionnez le menu d'actions de la stratégie d'instantanés, puis sélectionnez *Attribuer une stratégie au volume*.
. Dans la boîte de dialogue attribuer une stratégie de snapshot, sélectionnez une stratégie de snapshot à affecter au volume et vérifiez la planification de la règle.
+
Si la règle contient des snapshots immuables et que vous souhaitez l'utiliser, acceptez l'instruction.

. Sélectionnez *affecter*.


.Résultat
La politique de snapshots est attribuée au volume.



== Supprimer une politique de snapshots d'un volume

Supprimez une règle de snapshot d'un volume car vous ne souhaitez plus de snapshots du volume ou parce que vous souhaitez supprimer une règle de snapshot attribuée à plusieurs volumes. À <<Supprimer une règle de snapshot,supprimer une règle de snapshot>> qui est attribué plusieurs volumes, vous devez le supprimer manuellement de tous les volumes.

.Avant de commencer
Vous devez associer un lien pour supprimer une politique de snapshot. link:https://docs.netapp.com/us-en/workload-fsx-ontap/create-link.html["Apprenez à associer un lien existant ou à créer et associer un nouveau lien"]. Une fois le lien associé, revenez à cette opération.

.Étapes
. Connectez-vous à l'aide de l'un des link:https://docs.netapp.com/us-en/workload-setup-admin/console-experiences.html["expériences de la console"^].
. Dans *Stockage*, sélectionnez *Accéder au stockage*.
. Dans l'onglet *FSx pour ONTAP*, sélectionnez le menu d'actions du système de fichiers contenant le volume auquel attribuer une stratégie de snapshot, puis sélectionnez *Gérer*.
. Dans la présentation du système de fichiers, sélectionnez l'onglet *Storage VMS*.
. Dans l'onglet *VM de stockage*, sélectionnez le menu d'actions pour la machine virtuelle de stockage contenant le volume à protéger avec des snapshots planifiés, puis *Actions avancées*, puis *Gérer les stratégies de snapshot*.
. Sur la page de gestion des stratégies d'instantanés, sélectionnez le menu d'actions de la stratégie d'instantanés, puis sélectionnez *Attribuer une stratégie au volume*.
. Dans la boîte de dialogue affecter une stratégie de snapshot, sélectionnez *aucun* pour supprimer la stratégie de snapshot.
. Sélectionnez *affecter*.


.Résultat
La règle de snapshot est supprimée du volume.



== Supprimer une règle de snapshot

Supprimez une règle de snapshot lorsque vous n'en avez plus besoin.

Lorsqu'une règle de snapshot est attribuée à plusieurs volumes, vous devez la supprimer manuellement <<Supprimer une politique de snapshots d'un volume,retirez-le>>pour tous les volumes. Vous pouvez également <<Affecter une politique de snapshots à un volume,attribuez une autre politique de snapshots>>sélectionner les volumes.

.Étapes
. Connectez-vous à l'aide de l'un des link:https://docs.netapp.com/us-en/workload-setup-admin/console-experiences.html["expériences de la console"^].
. Dans *Stockage*, sélectionnez *Accéder au stockage*.
. Dans le menu Stockage, sélectionnez *FSx pour ONTAP*.
. Depuis *FSx for ONTAP*, sélectionnez le menu d'actions du système de fichiers avec le volume, puis sélectionnez *Gérer*.
. Dans la présentation du système de fichiers, sélectionnez l'onglet *Storage VMS*.
. Dans l'onglet *VM de stockage*, sélectionnez le menu d'actions de la machine virtuelle de stockage avec la stratégie de snapshot à supprimer, puis *Actions avancées*, puis *Gérer les stratégies de snapshot*.
. Sur la page de gestion des stratégies d'instantané, sélectionnez le menu d'actions pour la stratégie d'instantané à supprimer, puis sélectionnez *Supprimer*.
. Dans la boîte de dialogue Supprimer, sélectionnez *Supprimer* pour supprimer la stratégie.

