---
sidebar: sidebar 
permalink: manage-cifs-share.html 
keywords: cifs, CIFS, cifs share, change cifs share, update cifs share, modify cifs share 
summary: 'Modifiez le partage CIFS d"un volume en usine de workloads BlueXP  qui utilise le type de protocole SMB/CIFS.' 
---
= Gérer le partage CIFS d'un volume en usine de charges de travail BlueXP 
:allow-uri-read: 
:icons: font
:imagesdir: ./media/


[role="lead"]
La gestion du partage CIFS d'un volume dans l'usine de charges de travail BlueXP  implique de déterminer les utilisateurs et les groupes auxquels accorder l'accès et le type d'accès qui leur est donné.

.Avant de commencer
Déterminez les utilisateurs ou les groupes auxquels accorder l'accès et le type d'accès à leur donner.

.Étapes
. Connectez-vous à l'aide de l'un des link:https://docs.netapp.com/us-en/workload-setup-admin/console-experiences.html["expériences de la console"^].
. Dans stockage, sélectionnez *accéder à l'inventaire de stockage*.
. Dans l'onglet *FSX pour ONTAP*, sélectionnez le menu à trois points du système de fichiers avec le volume à mettre à jour, puis sélectionnez *gérer*.
. Dans la présentation du système de fichiers, sélectionnez l'onglet *volumes*.
. Dans l'onglet volumes, sélectionnez le menu à trois points du volume pour lequel modifier le partage SMB.
. Sélectionnez *actions avancées*, puis *Modifier le partage CIFS*.
. Sur la page Modifier le partage CIFS, indiquez les informations suivantes :
+
.. *Nom* : entrez le nom du partage CIFS.
.. *Autorisations* : sélectionnez contrôle total, lecture/écriture, lecture ou aucun accès, puis entrez les utilisateurs ou les groupes séparés par un point-virgule ( ; ). Les utilisateurs ou les groupes sont sensibles à la casse et le domaine de l'utilisateur doit être inclus au format « domaine\nom d'utilisateur ».


. Sélectionnez appliquer.
+
Les modifications peuvent entraîner la perte de l'accès des utilisateurs ou des groupes actuels au partage CIFS.

. Sélectionnez *Continuer* pour enregistrer les modifications.


.Résultat
Les modifications apportées au partage CIFS sont appliquées.
