---
sidebar: sidebar 
permalink: pause-resume-replication.html 
keywords: pause replication, quiesce replication, resume replication 
summary: Mettre en pause et reprendre une relation de réplication de sorte que le volume cible devienne le volume source. 
---
= Mettre en pause et reprendre une relation de réplication dans l'usine de charges de travail BlueXP 
:allow-uri-read: 
:icons: font
:imagesdir: ./media/


[role="lead"]
Mettre en pause une relation de réplication pour arrêter les mises à jour de réplication planifiées du volume source vers le volume cible. Le volume cible passe de lecture seule à lecture/écriture. Les deux volumes continuent de partager le dernier snapshot de réplication en tant que nouvelle base pour une resynchronisation ultérieure.

.Description de la tâche
En pause, la relation de réplication entre le volume source et le volume cible continue d'exister. Les transferts de données s'interrompe et les volumes deviennent indépendants. Pour réactiver le transfert des modifications du volume source vers le volume de destination, reprenez la réplication.

Lorsque vous reprenez une réplication, toutes les modifications apportées au volume cible sont annulées et l'usine de la charge de travail BlueXP  réactive la réplication. Le volume cible passe de la lecture/écriture à la lecture seule et reçoit à nouveau les mises à jour du volume source à l'intervalle de réplication planifié. Lorsque vous reprenez une relation de réplication, le volume cible revient au dernier snapshot de réplication initial, à ce moment-là, le processus de réplication du volume recommence.

.Avant de commencer
Si vous interrompez un transfert en cours, le transfert n'est pas affecté et la relation devient « suspendue » jusqu'à ce que le transfert soit terminé. Si le transfert en cours est interrompu, il s'agit maintenant d'un transfert ultérieur et ne redémarrera pas.



== Interrompre une relation de réplication

.Étapes
. Connectez-vous à l'aide de l'un des link:https://docs.netapp.com/us-en/workload-setup-admin/console-experiences.html["expériences de la console"^].
. Dans stockage, sélectionnez *accéder à l'inventaire de stockage*.
. Dans l'onglet *FSX pour ONTAP*, sélectionnez le menu à trois points du système de fichiers à mettre à jour, puis sélectionnez *gérer*.
. Dans la présentation du système de fichiers, sélectionnez l'onglet *relations de réplication*.
. Dans l'onglet Replication relations (relations de réplication), sélectionnez le menu à trois points de la relation de réplication à mettre en pause.
. Sélectionnez *Pause (Quiesce)*.
. Dans la boîte de dialogue *Quiesce Relationship*, sélectionnez *Quiesce*.


.Résultat
La relation s'interrompt et son état s'affiche en pause.



== Reprendre une relation de réplication interrompue

Lorsque vous reprenez une relation de réplication, toutes les modifications apportées au volume de destination pendant l'arrêt de la réplication sont supprimées.


NOTE: Toutes les données écrites sur le volume source d'origine entre la dernière réplication de données et l'heure à laquelle le volume source est désactivé ne sont pas conservées.

.Étapes
. Connectez-vous à l'aide de l'un des link:https://docs.netapp.com/us-en/workload-setup-admin/console-experiences.html["expériences de la console"^].
. Dans stockage, sélectionnez *accéder à l'inventaire de stockage*.
. Dans l'onglet *FSX pour ONTAP*, sélectionnez le menu à trois points du système de fichiers à mettre à jour, puis sélectionnez *gérer*.
. Dans la présentation du système de fichiers, sélectionnez l'onglet *relations de réplication*.
. Dans l'onglet relations de réplication, sélectionnez le menu à trois points de la relation de réplication à reprendre.
. Sélectionnez *reprendre*.
. Dans la boîte de dialogue reprendre la relation, sélectionnez *reprendre*.


.Résultat
La relation reprend et son état s'affiche comme « répliqué ».
