---
settings:
  name: Amazon FSx for NetApp ONTAP
  internal:
    pdf_enabled: true
    termcheck_enabled: true
  prod:
    pdf_enabled: true
    harmony_enabled: false
  rss_page: whats-new.html
  release_notes_autogen:
    release_notes_repo: workload-relnotes
  langs: fr-fr,us-en,de-de,es-es,it-it,pt-br,ja-jp,ko-kr,zh-cn,zh-tw
sidebar:
  entries:
  - title: Documents relatifs à Amazon FSX pour NetApp ONTAP
    url: "/index.html"
  - title: Notes de mise à jour
    entries:
    - title: Quoi de neuf
      url: "/whats-new.html"
    - title: Limites connues
      url: "/known-limitations.html"
  - title: Commencez
    entries:
    - title: Découvrez Amazon FSX pour NetApp ONTAP
      url: "/learn-fsx-ontap.html"
    - title: Démarrage rapide
      url: "/quick-start.html"
    - title: Créez un système de fichiers FSX pour ONTAP
      url: "/create-file-system.html"
  - title: Utilisez Amazon FSX pour NetApp ONTAP
    entries:
    - title: Découvrez les économies
      url: "/explore-savings.html"
    - title: Suivre et analyser les coûts FSx pour ONTAP
      url: "/track-costs.html"
    - title: Utiliser les liens
      entries:
      - title: En savoir plus sur les liens
        url: "/links-overview.html"
      - title: Connectez-vous à un système de fichiers avec un lien
        url: "/create-link.html"
      - title: Gérer les liens
        url: "/manage-links.html"
    - title: Découvrir et afficher les volumes de cache
      url: "/discover-cache-volumes.html"
    - title: Gérer les volumes
      entries:
      - title: Créer un volume
        url: "/create-volume.html"
      - title: Accès à vos données
        url: "/access-data.html"
    - title: Créer des ressources de stockage bloc
      entries:
      - title: Créer un igroup
        url: "/create-igroup.html"
      - title: Créer un périphérique de bloc
        url: "/create-block-device.html"
    - title: Créez une machine virtuelle de stockage
      url: "/create-storage-vm.html"
    - title: Protégez vos données
      entries:
      - title: Présentation de la protection des données
        url: "/data-protection-overview.html"
      - title: Utiliser des instantanés
        entries:
        - title: Créer un snapshot
          url: "/create-snapshot.html"
        - title: Création d'une règle de snapshots
          url: "/create-snapshot-policy.html"
        - title: Restaurer un volume à partir d'un snapshot
          url: "/restore-volume-from-snapshot.html"
      - title: Utiliser des sauvegardes pour le stockage d'objets
        entries:
        - title: Créez une sauvegarde manuelle
          url: "/create-backup.html"
        - title: Restaurer un volume à partir d'une sauvegarde
          url: "/restore-from-backup.html"
      - title: Utiliser la réplication
        entries:
        - title: Créer une relation de réplication
          url: "/create-replication.html"
        - title: Initialiser une relation de réplication
          url: "/initialize-replication.html"
      - title: Protégez vos données avec la protection anti-ransomware autonome
        url: "/ransomware-protection.html"
      - title: Clonez un volume
        url: "/clone-volume.html"
      - title: Utilisation des données ONTAP sur site
        url: "/use-onprem-data.html"
      - title: Créer un coffre-fort numérique pour protéger les données
        url: "/create-cyber-vault.html"
  - title: Administration et contrôle
    entries:
    - title: Surveiller les opérations avec Tracker
      url: "/monitor-operations.html"
    - title: Mettez en œuvre les bonnes pratiques en matière de système de fichiers
      entries:
      - title: Analyse de la configuration de FSX pour ONTAP
        url: "/configuration-analysis.html"
      - title: Implémenter des configurations de système de fichiers bien architecturées
        url: "/improve-configurations.html"
    - title: Analyse des événements FSx pour ONTAP EMS
      url: "/analyze-events.html"
    - title: L'administration des volumes
      entries:
      - title: Modifier la croissance automatique du volume
        url: "/edit-volume-autogrow.html"
      - title: Ajuster la capacité du volume
        url: "/adjust-volume-capacity.html"
      - title: Rééquilibrer la capacité du volume
        url: "/rebalance-volume.html"
      - title: Gérer les fichiers immuables
        url: "/manage-immutable-files.html"
      - title: Gérer les balises de volume
        url: "/manage-volume-tags.html"
      - title: Gérer les volumes de cache
        url: "/manage-cache-volumes.html"
      - title: Modifier une règle de hiérarchisation
        url: "/change-tiering-policy.html"
      - title: Mise à jour de l'efficacité du stockage
        url: "/update-storage-efficiency.html"
      - title: Gestion des règles d'exportation NFS
        url: "/manage-nfs-export-policy.html"
      - title: Gérer les partages SMB/CIFS
        url: "/manage-cifs-share.html"
      - title: Gérer les points d'accès S3
        url: "/manage-s3-access-points.html"
      - title: Diviser un volume cloné
        url: "/split-cloned-volume.html"
      - title: Supprimer un volume
        url: "/delete-volume.html"
    - title: Administration du stockage bloc
      entries:
      - title: Gérer les igroups
        url: "/manage-igroups.html"
      - title: Gérer les périphériques de blocage
        url: "/manage-block-devices.html"
    - title: Administration du système de fichiers
      entries:
      - title: Ajuster la capacité du système de fichiers
        url: "/increase-file-system-capacity.html"
      - title: Activer la gestion automatique de la capacité et des inodes
        url: "/enable-auto-capacity-management.html"
      - title: Gérer les balises du système de fichiers
        url: "/manage-fsx-tags.html"
      - title: Réinitialisez le mot de passe fsxadmin
        url: "/reset-fsxadmin-password.html"
      - title: Supprimer un système de fichiers
        url: "/delete-file-system.html"
    - title: Administration des machines virtuelles de stockage
      entries:
      - title: Réplication d'une VM de stockage vers un autre système de fichiers
        url: "/replicate-svm-to-file-system.html"
      - title: Configurer et mettre à jour Active Directory pour une VM de stockage
        url: "/configure-active-directory.html"
      - title: Gestion des balises des VM de stockage
        url: "/manage-svm-tags.html"
      - title: Réinitialiser le mot de passe de la VM de stockage
        url: "/reset-svm-password.html"
      - title: Supprimer une machine virtuelle de stockage
        url: "/delete-svm.html"
    - title: Administration de la protection des données
      entries:
      - title: Snapshots
        entries:
        - title: Gérer les règles relatives aux snapshots
          url: "/manage-snapshot-policy.html"
        - title: Activez et modifiez les snapshots pour une conservation à long terme
          url: "/enable-snapshots-long-term.html"
        - title: Gérer les snapshots
          url: "/manage-snapshots.html"
      - title: Sauvegardes
        entries:
        - title: Gérez la planification des sauvegardes FSX pour ONTAP
          url: "/manage-backup-schedule.html"
      - title: La réplication
        entries:
        - title: Réplication d'un volume de protection des données
          url: "/cascade-replication.html"
        - title: Inverser une relation de réplication
          url: "/reverse-replication.html"
        - title: Modifier la planification de réplication d'un volume source
          url: "/change-replication-schedule.html"
        - title: Limitez le taux de transfert maximal d'une relation de réplication
          url: "/limit-transfer-rate.html"
        - title: Mise à jour manuelle des données de snapshot dans une relation de
            réplication
          url: "/update-snapshot-replication.html"
        - title: Mettre en pause et reprendre une relation de réplication
          url: "/pause-resume-replication.html"
        - title: Arrête une relation de réplication
          url: "/stop-replication.html"
        - title: Supprimer une relation de réplication
          url: "/delete-replication.html"
    - title: Administration des performances
      entries:
      - title: Provisionnez les IOPS pour un système de fichiers
        url: "/provision-iops.html"
      - title: Mettre à jour la capacité de débit d'un système de fichiers
        url: "/update-throughput-capacity.html"
  - title: Référence
    entries:
    - title: Performances de FSX pour ONTAP
      url: "/performance-reference.html"
    - title: Sécurité pour FSX for ONTAP
      url: "/security-reference.html"
  - title: Connaissances et support
    entries:
    - title: S'inscrire pour obtenir de l'aide
      url: "/support-registration.html"
    - title: Obtenez de l'aide
      url: "/get-help.html"
    - title: Dépannage
      url: "/troubleshooting.html"
  - title: Mentions légales
    url: "/legal-notices.html"
product-family:
  name: NetApp Workload Factory
  repo: workload-family
