---
settings:
  name: Amazon FSx for NetApp ONTAP
  platform: cloud
  internal:
    pdf_enabled: true
    termcheck_enabled: true
  prod:
    pdf_enabled: true
    harmony_enabled: false
  rss_page: whats-new.html
  release_notes_autogen:
    release_notes_repo: workload-relnotes
  langs: fr-fr,us-en,de-de,es-es,it-it,pt-br,ja-jp,ko-kr,zh-cn,zh-tw
sidebar:
  entries:
  - title: Documents relatifs à Amazon FSX pour NetApp ONTAP
    url: "/index.html"
  - title: Notes de mise à jour
    entries:
    - title: Quoi de neuf
      url: "/whats-new.html"
    - title: Limites connues
      url: "/known-limitations.html"
  - title: Commencez
    entries:
    - title: Découvrez Amazon FSX pour NetApp ONTAP
      url: "/learn-fsx-ontap.html"
    - title: Démarrage rapide
      url: "/quick-start.html"
    - title: Créez un système de fichiers FSX pour ONTAP
      url: "/create-file-system.html"
  - title: Utilisez Amazon FSX pour NetApp ONTAP
    entries:
    - title: Découvrez les économies
      url: "/explore-savings.html"
    - title: Utiliser les liens
      entries:
      - title: Présentation des liens
        url: "/links-overview.html"
      - title: Créer un lien
        url: "/create-link.html"
      - title: Gérer les liens
        url: "/manage-links.html"
    - title: Gérer les volumes
      entries:
      - title: Créer un volume
        url: "/create-volume.html"
      - title: Accès à vos données
        url: "/access-data.html"
    - title: Créez une machine virtuelle de stockage
      url: "/create-storage-vm.html"
    - title: Protégez vos données
      entries:
      - title: Présentation de la protection des données
        url: "/data-protection-overview.html"
      - title: Gérer les snapshots
        entries:
        - title: Créer un snapshot
          url: "/create-snapshot.html"
        - title: Création d'une règle de snapshots
          url: "/create-snapshot-policy.html"
        - title: Restaurer un volume à partir d'un snapshot
          url: "/restore-volume-from-snapshot.html"
        - title: Créez un volume à partir d'un snapshot
          url: "/create-volume-from-snapshot.html"
      - title: Gérez les sauvegardes vers un stockage objet
        entries:
        - title: Créez une sauvegarde manuelle
          url: "/create-backup.html"
        - title: Restaurer un volume à partir d'une sauvegarde
          url: "/restore-from-backup.html"
      - title: Gérer la réplication
        entries:
        - title: Créer une relation de réplication
          url: "/create-replication.html"
        - title: Initialiser une relation de réplication
          url: "/initialize-replication.html"
      - title: Clonez un volume
        url: "/clone-volume.html"
      - title: Utilisation des données ONTAP sur site
        url: "/use-onprem-data.html"
  - title: Administration et contrôle
    entries:
    - title: L'administration des volumes
      entries:
      - title: Modifier la croissance automatique du volume
        url: "/edit-volume-autogrow.html"
      - title: Augmentez la capacité du volume
        url: "/increase-volume-capacity.html"
      - title: Gérer les balises de volume
        url: "/manage-volume-tags.html"
      - title: Rééquilibrage de la capacité d'un volume
        url: "/rebalance-volume.html"
      - title: Modifier une règle de hiérarchisation
        url: "/change-tiering-policy.html"
      - title: Mise à jour de l'efficacité du stockage
        url: "/update-storage-efficiency.html"
      - title: Gestion des règles d'exportation NFS
        url: "/manage-nfs-export-policy.html"
      - title: Gérer les partages CIFS
        url: "/manage-cifs-share.html"
      - title: Diviser un volume cloné
        url: "/split-cloned-volume.html"
      - title: Supprimer un volume
        url: "/delete-volume.html"
    - title: Administration du système de fichiers
      entries:
      - title: Augmenter la capacité du système de fichiers
        url: "/increase-file-system-capacity.html"
      - title: Activez la gestion automatique de la capacité
        url: "/enable-auto-capacity-management.html"
      - title: Réinitialisez le mot de passe fsxadmin
        url: "/reset-fsxadmin-password.html"
      - title: Supprimer un système de fichiers
        url: "/delete-file-system.html"
    - title: Administration des machines virtuelles de stockage
      entries:
      - title: Réplication d'une VM de stockage vers un autre système de fichiers
        url: "/replicate-svm-to-file-system.html"
      - title: Configurer et mettre à jour Active Directory pour une VM de stockage
        url: "/configure-active-directory.html"
      - title: Gestion des balises des VM de stockage
        url: "/manage-svm-tags.html"
      - title: Réinitialiser le mot de passe de la VM de stockage
        url: "/reset-svm-password.html"
      - title: Supprimer une machine virtuelle de stockage
        url: "/delete-svm.html"
    - title: Administration de la protection des données
      entries:
      - title: Modifier la règle de snapshot d'un volume
        url: "/change-snapshot-policy.html"
      - title: Gérez la planification des sauvegardes FSX pour ONTAP
        url: "/manage-backup-schedule.html"
      - title: Activez et modifiez les snapshots pour une conservation à long terme
        url: "/enable-snapshots-long-term.html"
      - title: Inverser une relation de réplication
        url: "/reverse-replication.html"
      - title: Modifier la planification de réplication d'un volume source
        url: "/change-replication-schedule.html"
      - title: Limitez le taux de transfert maximal d'une relation de réplication
        url: "/limit-transfer-rate.html"
      - title: Mise à jour manuelle des données de snapshot dans une relation de réplication
        url: "/update-snapshot-replication.html"
      - title: Arrête une relation de réplication
        url: "/stop-replication.html"
      - title: Supprimer une relation de réplication
        url: "/delete-replication.html"
    - title: Administration des performances
      entries:
      - title: Provisionnez les IOPS pour un système de fichiers
        url: "/provision-iops.html"
      - title: Mettre à jour la capacité de débit d'un système de fichiers
        url: "/update-throughput-capacity.html"
  - title: Référence
    entries:
    - title: Performances de FSX pour ONTAP
      url: "/performance-reference.html"
    - title: Sécurité pour FSX for ONTAP
      url: "/security-reference.html"
  - title: Connaissances et support
    entries:
    - title: S'inscrire pour obtenir de l'aide
      url: "/support-registration.html"
    - title: Obtenez de l'aide
      url: "/get-help.html"
    - title: Dépannage
      url: "/troubleshooting.html"
  - title: Mentions légales
    url: "/legal-notices.html"
product-family:
  name: BlueXP workload factory
  repo: workload-family
