---
sidebar: sidebar 
permalink: replicate-svm-to-file-system.html 
keywords:  
summary: 'La réplication d"une machine virtuelle de stockage vers un autre système de fichiers FSX for ONTAP offre une couche de protection d"accès aux données en cas de perte de données.' 
---
= Réplication d'une VM de stockage vers un autre système de fichiers FSX pour ONTAP
:allow-uri-read: 
:icons: font
:imagesdir: ./media/


[role="lead"]
La réplication d'une machine virtuelle de stockage vers un autre système de fichiers FSx for ONTAP dans NetApp Workload Factory fournit une couche de protection d'accès aux données en cas de perte de données.  Cette opération réplique tous les volumes d'une machine virtuelle de stockage vers un autre système de fichiers FSx pour ONTAP .

.Avant de commencer
Pour répliquer une machine virtuelle de stockage vers un autre système de fichiers FSx for ONTAP, vous devez associer un lien. link:https://docs.netapp.com/us-en/workload-fsx-ontap/create-link.html["Apprenez à associer un lien existant ou à créer et associer un nouveau lien"]. Une fois le lien associé, revenez à cette opération.

.Étapes
. Connectez-vous à l'aide de l'un des link:https://docs.netapp.com/us-en/workload-setup-admin/console-experiences.html["expériences de la console"^].
. Dans la mosaïque Stockage, sélectionnez *Accéder au stockage*.
. Dans le menu Stockage, sélectionnez *FSx pour ONTAP*.
. Depuis *FSx for ONTAP*, sélectionnez le menu d'actions du système de fichiers avec la machine virtuelle de stockage à répliquer, puis sélectionnez *Gérer*.
. Dans la vue d'ensemble du système de fichiers sous Machines virtuelles de stockage, sélectionnez *Gérer*.
. Sur l'écran Gérer les machines virtuelles de stockage, sélectionnez le menu actions de la machine virtuelle de stockage pour laquelle vous souhaitez répliquer une SVM, puis sélectionnez *Actions avancées* > *Répliquer la machine virtuelle de stockage*.
. Sur la page de données répliquées, sous cible de réplication, indiquez les informations suivantes :
+
.. *FSX pour système de fichiers ONTAP* : sélectionnez les informations d'identification, la région et le nom du système de fichiers FSX pour ONTAP pour le système de fichiers cible FSX pour ONTAP.
.. *Nom de la VM de stockage* : sélectionnez la VM de stockage dans le menu déroulant.
.. *Nom du volume* : le nom du volume cible est généré automatiquement au format suivant `{OriginalVolumeName}_copy`.
.. *Règle de hiérarchisation* : sélectionnez la règle de hiérarchisation pour les données stockées dans le volume cible.
+
_Auto_ est la stratégie de hiérarchisation par défaut lors de la création d'un volume à l'aide de l'interface utilisateur Workload Factory FSx for ONTAP .  Pour plus d'informations sur les politiques de hiérarchisation des volumes, reportez-vous àlink:https://docs.aws.amazon.com/fsx/latest/ONTAPGuide/volume-storage-capacity.html#data-tiering-policy["Capacité de stockage du volume"^] dans la documentation AWS FSx pour NetApp ONTAP .

.. *Taux de transfert max.* : sélectionnez *Limited* et entrez la limite de transfert max. En Mo/s. Vous pouvez également sélectionner *Illimité*.
+
Sans limite, les performances du réseau et des applications peuvent diminuer. Nous recommandons également un taux de transfert illimité pour les systèmes de fichiers FSX pour ONTAP pour les workloads stratégiques, par exemple ceux utilisés principalement pour la reprise d'activité.



. Sous Paramètres de réplication, fournissez les informations suivantes :
+
.. *Intervalle de réplication* : sélectionnez la fréquence à laquelle les instantanés sont transférés du volume source vers le volume cible.
.. *Conservation à long terme* : éventuellement, activez les instantanés pour la conservation à long terme.
+
Si vous activez la conservation à long terme, sélectionnez une règle existante ou créez une nouvelle règle pour définir les snapshots à répliquer et le nombre à conserver.

+
... Pour *Choisissez une stratégie existante*, sélectionnez une stratégie existante dans le menu déroulant.
... Pour *Créer une nouvelle police*, fournissez les éléments suivants :
+
.... *Nom de la stratégie* : entrez un nom de stratégie.
.... *Stratégies Snapshot* : dans le tableau, sélectionnez la fréquence de la règle de snapshot et le nombre de copies à conserver. Vous pouvez sélectionner plusieurs règles de snapshot.






. Sélectionnez *Créer*.


.Résultat
Tous les volumes de la VM de stockage sont répliqués sur le système de fichiers cible.
