---
sidebar: sidebar 
permalink: reset-svm-password.html 
keywords: reset storage vm password, reset svm password 
summary: 'Si nécessaire, réinitialisez le mot de passe d"une machine virtuelle de stockage en usine de charges de travail BlueXP .' 
---
= Réinitialise le mot de passe de la machine virtuelle de stockage en usine de la charge de travail BlueXP 
:allow-uri-read: 
:icons: font
:imagesdir: ./media/


[role="lead"]
Si nécessaire, réinitialisez le mot de passe d'une machine virtuelle de stockage en usine de charges de travail BlueXP .

.Étapes
. Connectez-vous à l'aide de l'un des link:https://docs.netapp.com/us-en/workload-setup-admin/console-experiences.html["expériences de la console"^].
. Dans stockage, sélectionnez *accéder à l'inventaire de stockage*.
. Dans l'onglet *FSX pour ONTAP*, sélectionnez le menu à trois points du système de fichiers FSX pour ONTAP avec la machine virtuelle de stockage à mettre à jour, puis sélectionnez *gérer*.
. Dans l'onglet Présentation du système de fichiers, sélectionnez l'onglet *Storage VMS*.
. Sous l'onglet Storage VMs, sélectionnez le menu à trois points de la VM de stockage pour lequel réinitialiser le mot de passe.
. Sélectionnez *Réinitialiser le mot de passe*.
. Dans la boîte de dialogue Réinitialiser le mot de passe, entrez les informations suivantes :
+
.. *Nouveau mot de passe* : saisissez un nouveau mot de passe pour la machine virtuelle de stockage.
.. *Confirmer le mot de passe* : saisissez à nouveau le nouveau mot de passe pour confirmer.


. Sélectionnez *appliquer*.

