---
sidebar: sidebar 
permalink: reset-svm-password.html 
keywords: reset storage vm password, reset svm password 
summary: 'Réinitialisez le mot de passe d"une machine virtuelle de stockage dans NetApp Workload Factory si nécessaire.' 
---
= Réinitialiser le mot de passe de la machine virtuelle de stockage dans NetApp Workload Factory
:allow-uri-read: 
:icons: font
:imagesdir: ./media/


[role="lead"]
Réinitialisez le mot de passe d'une machine virtuelle de stockage dans NetApp Workload Factory si nécessaire.

.Étapes
. Connectez-vous à l'aide de l'un des link:https://docs.netapp.com/us-en/workload-setup-admin/console-experiences.html["expériences de la console"^].
. Depuis Stockage, sélectionnez *Accéder au stockage*.
. Dans le menu Stockage, sélectionnez *FSx pour ONTAP*.
. Dans *FSx for ONTAP*, sélectionnez le menu actions du système de fichiers contenant le mot de passe de la machine virtuelle de stockage à réinitialiser, puis sélectionnez *Gérer*.
. Dans la vue d'ensemble du système de fichiers sous Machines virtuelles de stockage, sélectionnez *Gérer*.
. Depuis l'écran Gérer les machines virtuelles de stockage, sélectionnez le menu Actions de la machine virtuelle de stockage dont vous souhaitez réinitialiser le mot de passe, puis sélectionnez *Actions de base* > *Réinitialiser le mot de passe*.
. Dans la boîte de dialogue Réinitialiser le mot de passe, entrez les informations suivantes :
+
.. *Nouveau mot de passe* : saisissez un nouveau mot de passe pour la machine virtuelle de stockage.
.. *Confirmer le mot de passe* : saisissez à nouveau le nouveau mot de passe pour confirmer.


. Sélectionnez *appliquer*.

