---
sidebar: sidebar 
permalink: reset-svm-password.html 
keywords: reset storage vm password, reset svm password 
summary: Réinitialisez le mot de passe de la VM de stockage si nécessaire. 
---
= Réinitialise le mot de passe d'une machine virtuelle de stockage
:allow-uri-read: 
:icons: font
:imagesdir: ./media/


[role="lead"]
Réinitialisez le mot de passe de la VM de stockage si nécessaire.

.Étapes
. Connectez-vous à la console Workload Factory.
. Dans stockage, sélectionnez *accéder à l'inventaire de stockage*.
. Sélectionnez l'onglet *VM de stockage*.
. Sous l'onglet Storage VMs, sélectionnez le menu Three DOTS de la machine virtuelle de stockage pour lequel réinitialiser le mot de passe.
. Sélectionnez *Réinitialiser le mot de passe*.
. Dans la boîte de dialogue Réinitialiser le mot de passe, entrez les informations suivantes :
+
.. *Nouveau mot de passe* : saisissez un nouveau mot de passe pour la machine virtuelle de stockage.
.. *Confirmer le mot de passe* : saisissez à nouveau le nouveau mot de passe pour confirmer.


. Cliquez sur *appliquer*.

