---
sidebar: sidebar 
permalink: reset-svm-password.html 
keywords: reset storage vm password, reset svm password 
summary: 'Réinitialisez le mot de passe d"une machine virtuelle de stockage dans NetApp Workload Factory si nécessaire.' 
---
= Réinitialiser le mot de passe de la machine virtuelle de stockage dans NetApp Workload Factory
:allow-uri-read: 
:icons: font
:imagesdir: ./media/


[role="lead"]
Réinitialisez le mot de passe d'une machine virtuelle de stockage dans NetApp Workload Factory si nécessaire.

.Étapes
. Connectez-vous à l'aide de l'un des link:https://docs.netapp.com/us-en/workload-setup-admin/console-experiences.html["expériences de la console"^].
. Depuis Stockage, sélectionnez *Accéder au stockage*.
. Dans le menu Stockage, sélectionnez *FSx pour ONTAP*.
. Depuis *FSx for ONTAP*, sélectionnez le menu d'actions du système de fichiers FSx for ONTAP avec la machine virtuelle de stockage à mettre à jour, puis sélectionnez *Gérer*.
. Dans l'onglet Présentation du système de fichiers, sélectionnez l'onglet *Storage VMS*.
. Dans l’onglet Machines virtuelles de stockage, sélectionnez le menu d’actions de la machine virtuelle de stockage pour laquelle réinitialiser le mot de passe.
. Sélectionnez *Réinitialiser le mot de passe*.
. Dans la boîte de dialogue Réinitialiser le mot de passe, entrez les informations suivantes :
+
.. *Nouveau mot de passe* : saisissez un nouveau mot de passe pour la machine virtuelle de stockage.
.. *Confirmer le mot de passe* : saisissez à nouveau le nouveau mot de passe pour confirmer.


. Sélectionnez *appliquer*.

