---
sidebar: sidebar 
permalink: reverse-replication.html 
keywords: reverse replication, change replication 
summary: Inversez une relation de réplication de sorte que le volume cible devienne le volume source. 
---
= Inverse une relation de réplication dans l'usine de workloads BlueXP 
:allow-uri-read: 
:icons: font
:imagesdir: ./media/


[role="lead"]
Inversez une relation de réplication en usine de workloads BlueXP  afin que le volume cible devienne le volume source.

Après avoir arrêté la réplication et modifié le volume cible, vous pouvez répliquer ces modifications sur le volume source. Ce processus est courant dans un scénario de reprise d'activité dans lequel vous travaillez sur le volume cible pendant un certain temps et souhaitez changer de rôle pour les volumes.

.Description de la tâche
Lorsque vous inversez et reprenez une réplication, elle change les rôles source et cible de vos volumes ; le volume cible devient le nouveau volume source et le volume source devient le nouveau volume cible. L'opération inverse écrase également le contenu du nouveau volume cible avec le contenu du nouveau volume source. Si vous inversez deux fois une réplication, le sens de réplication d'origine se rétablit.


NOTE: Toutes les données écrites sur le volume source d'origine entre la dernière réplication de données et l'heure à laquelle le volume source est désactivé ne sont pas conservées.

.Avant de commencer
Assurez-vous de connaître les rôles actuels et futurs de vos volumes source et cible car les modifications du nouveau volume cible sont remplacées par le nouveau volume source. Une mauvaise utilisation peut entraîner des pertes de données imprévues.

.Étapes
. Connectez-vous à l'aide de l'un des link:https://docs.netapp.com/us-en/workload-setup-admin/console-experiences.html["expériences de la console"^].
. Dans stockage, sélectionnez *accéder à l'inventaire de stockage*.
. Dans l'onglet *FSX pour ONTAP*, sélectionnez le menu à trois points du système de fichiers à mettre à jour, puis sélectionnez *gérer*.
. Dans la présentation du système de fichiers, sélectionnez l'onglet *relations de réplication*.
. Dans l'onglet relations de réplication, sélectionnez le menu à trois points de la relation de réplication à inverser.
. Sélectionnez *Inverser la relation*.
. Dans la boîte de dialogue Inverser la relation, sélectionnez *Inverser*.

