---
sidebar: sidebar 
permalink: split-cloned-volume.html 
keywords: split clone volume, FlexVol volume 
summary: Séparez un volume FlexVol clone de son volume parent pour en faire un volume FlexVol en lecture-écriture standard. 
---
= Diviser un volume cloné
:allow-uri-read: 
:icons: font
:imagesdir: ./media/


[role="lead"]
Séparez un volume FlexVol clone de son volume parent pour en faire un volume FlexVol en lecture-écriture standard.

Les données sont accessibles sur le clone et sur le parent lors du fractionnement. Le processus de fractionnement ne met à jour que les métadonnées et requiert un nombre d'E/S minimal. Aucun bloc de données n'est copié.

.Description de la tâche
L'opération de fractionnement du clone implique les opérations suivantes :

* Il est impossible de créer de nouvelles copies Snapshot du volume FlexClone au cours de la division.
* Un volume FlexClone ne peut pas être séparé du volume parent s'il appartient à une relation de protection des données.
* Si vous mettez le volume FlexClone hors ligne alors que le fractionnement est en cours, l'opération est suspendue. Lorsque vous remettez le volume FlexClone en ligne, l'opération de fractionnement reprend.
* Après le fractionnement, le volume FlexVol parent et le clone nécessitent l'allocation d'espace complet déterminée par leurs garanties de volume.
* Une fois qu'un volume FlexClone est séparé de son parent, il n'est pas possible de le rejoindre à nouveau.


.Avant de commencer
Avant de fractionner un volume cloné, tenez compte des points suivants :

* Pour fractionner un volume cloné, vous devez link:manage-links.html["associer un lien"]. Si vous n'avez pas de lien existant, link:create-link.html["créer un lien"]. Pour associer un lien dans le système de fichiers, cliquez sur *lien associé* sous *Nom du compte*. Une fois le lien associé, revenez à cette opération.
* Vous devez être un administrateur de cluster.
* Le volume FlexClone doit être en ligne au début de l'opération de fractionnement.
* Le volume parent doit être en ligne pour que le fractionnement réussisse.


.Étapes
. Connectez-vous au link:https://console.workloads.netapp.com/["Console Workload Factory"^]
. Dans stockage, sélectionnez *accéder à l'inventaire de stockage*.
. Sélectionnez l'onglet *volumes*.
. Dans l'onglet volumes, sélectionnez le menu à trois points du volume avec le volume cloné à diviser.
. Sélectionnez *actions de protection des données*, puis *diviser le volume cloné*.
. Dans la boîte de dialogue diviser le volume, cliquez sur *Supprimer*.

