---
sidebar: sidebar 
permalink: split-cloned-volume.html 
keywords: split clone volume, FlexVol volume 
summary: Séparez une FlexVol volume de clone de son volume parent pour en faire une FlexVol volume de lecture/écriture standard. 
---
= Diviser un volume cloné dans NetApp Workload Factory
:allow-uri-read: 
:icons: font
:imagesdir: ./media/


[role="lead"]
Divisez un FlexVol volume cloné de son volume parent pour faire du clone un FlexVol volume en lecture/écriture normal dans NetApp Workload Factory.

Les données sont accessibles sur le clone et sur le parent lors du fractionnement. Le processus de fractionnement ne met à jour que les métadonnées et requiert un nombre d'E/S minimal. Aucun bloc de données n'est copié.

.Description de la tâche
L'opération de fractionnement du clone implique les opérations suivantes :

* Il est impossible de créer de nouvelles copies Snapshot du volume FlexClone au cours de la division.
* Un volume FlexClone ne peut pas être séparé du volume parent s'il appartient à une relation de protection des données.
* Si vous mettez le volume FlexClone hors ligne alors que le fractionnement est en cours, l'opération est suspendue. Lorsque vous remettez le volume FlexClone en ligne, l'opération de fractionnement reprend.
* Après le fractionnement, le volume FlexVol parent et le clone nécessitent l'allocation d'espace complet déterminée par leurs garanties de volume.
* Une fois qu'un volume FlexClone est séparé de son parent, il n'est pas possible de le rejoindre à nouveau.


.Avant de commencer
Avant de fractionner un volume cloné, tenez compte des points suivants :

* Pour diviser un volume cloné, vous devez associer un lien. link:https://docs.netapp.com/us-en/workload-fsx-ontap/create-link.html["Apprenez à associer un lien existant ou à créer et associer un nouveau lien"]. Une fois le lien associé, revenez à cette opération.
* Le volume FlexClone doit être en ligne au début de l'opération de fractionnement.
* Le volume parent doit être en ligne pour que le fractionnement réussisse.


.Étapes
. Connectez-vous à l'aide de l'un des link:https://docs.netapp.com/us-en/workload-setup-admin/console-experiences.html["expériences de la console"^].
. Dans la mosaïque Stockage, sélectionnez *Accéder au stockage*.
. Dans le menu Stockage, sélectionnez *FSx pour ONTAP*.
. Depuis *FSx for ONTAP*, sélectionnez le menu d'actions du système de fichiers avec le volume cloné à diviser, puis sélectionnez *Gérer*.
. Dans la présentation du système de fichiers, sélectionnez l'onglet *volumes*.
. Dans l’onglet Volumes, sélectionnez le menu d’actions du volume avec le volume cloné à diviser.
. Sélectionnez *actions de protection des données*, puis *diviser le volume cloné*.
. Dans la boîte de dialogue diviser le volume, sélectionnez *Supprimer*.


.Résultat
Le clone de volume est divisé et apparaît dans l'onglet volumes.
