---
sidebar: sidebar 
permalink: update-snapshot-replication.html 
keywords: update snapshot data, replication 
summary: Mettez à jour manuellement à tout moment les données de snapshot transférées entre les volumes source et cible dans une relation de réplication. 
---
= Mettre à jour les données d'instantané dans une relation de réplication
:allow-uri-read: 
:icons: font
:imagesdir: ./media/


[role="lead"]
Une relation de réplication dispose d'un planning de réplication défini, mais vous pouvez à tout moment mettre à jour manuellement les données d'instantané transférées entre les volumes source et cible dans l'usine de workloads BlueXP .

.Étapes
. Connectez-vous à l'aide de l'un des link:https://docs.netapp.com/us-en/workload-setup-admin/console-experiences.html["expériences de la console"^].
. Dans stockage, sélectionnez *accéder à l'inventaire de stockage*.
. Dans l'onglet *FSX pour ONTAP*, sélectionnez le menu à trois points du système de fichiers à mettre à jour, puis sélectionnez *gérer*.
. Dans la présentation du système de fichiers, sélectionnez l'onglet *relations de réplication*.
. Dans l'onglet relations de réplication, sélectionnez le menu à trois points de la relation de réplication à mettre à jour.
. Sélectionnez *mettre à jour maintenant*.
. Dans la boîte de dialogue mise à jour, sélectionnez *mettre à jour maintenant*.

