---
sidebar: sidebar 
permalink: whats-new.html 
keywords: 'what"s new, features, new, release notes, enhancements, fixes, new features, workload factory, amazon fsx' 
summary: 'Découvrez les nouveautés d"Amazon FSX pour NetApp ONTAP.' 
---
= Quoi de neuf
:allow-uri-read: 
:icons: font
:imagesdir: ./media/


[role="lead"]
Découvrez les nouveautés d'Amazon FSX pour NetApp ONTAP.



== 4 août



=== Prise en charge de Terraform

Vous pouvez désormais utiliser Terraform à partir de Codebox pour déployer et gérer des systèmes de fichiers et des machines virtuelles de stockage.

* link:create-file-system.html["Créez un système de fichiers"]
* link:create-storage-vm.html["Créez une machine virtuelle de stockage"]
* link:https://docs.netapp.com/us-en/workload-setup-admin/use-codebox.html["Utiliser Terraform à partir de Codebox"^]




=== Recommandations de débit et d'IOPS dans le calculateur de stockage

Le calculateur de stockage fait des recommandations de configuration de système de fichiers FSX pour ONTAP pour le débit et les IOPS en fonction des bonnes pratiques AWS, qui vous guide de façon optimale pour votre sélection.



== 7 juillet

Amazon FSX pour NetApp ONTAP est désormais disponible dans BlueXP Workload Factory.

link:learn-fsx-ontap.html["Découvrez BlueXP Workload Factory pour Amazon FSX pour NetApp ONTAP"].
