---
sidebar: sidebar 
permalink: whats-new.html 
keywords: 'what"s new, features, new, release notes, enhancements, fixes, new features, workload factory, amazon fsx for netapp ontap, fsx for ontap' 
summary: 'Découvrez les nouveautés d"Amazon FSX pour NetApp ONTAP.' 
---
= Quoi de neuf
:allow-uri-read: 
:icons: font
:imagesdir: ./media/


[role="lead"]
Découvrez les nouveautés d'Amazon FSX pour NetApp ONTAP.



== 1er septembre 2024



=== Prise en charge du mode de lecture pour la gestion du stockage

Le mode de lecture est disponible pour la gestion du stockage dans Workload Factory. Le mode lecture améliore l'expérience du mode de base en ajoutant des autorisations en lecture seule afin que les modèles Infrastructure-as-Code soient remplis avec vos variables spécifiques. Les modèles Infrastructure-as-Code peuvent être exécutés directement depuis votre compte AWS sans permissions de modification pour Workload Factory.

link:https://docs.netapp.com/us-en/workload-setup-admin/operational-modes.html["En savoir plus sur le mode lecture"^]



=== Prise en charge de la sauvegarde avant suppression de volume

Vous pouvez à présent sauvegarder un volume avant de le supprimer. La sauvegarde restera dans le système de fichiers jusqu'à sa suppression.

link:https://docs.netapp.com/us-en/workload-fsx-ontap/delete-volume.html["Supprimer un volume"^]



== 4 août 2024



=== Prise en charge de Terraform

Vous pouvez désormais utiliser Terraform à partir de Codebox pour déployer des systèmes de fichiers et des machines virtuelles de stockage.

* link:https://docs.netapp.com/us-en/workload-fsx-ontap/create-file-system.html["Créez un système de fichiers"]
* link:https://docs.netapp.com/us-en/workload-fsx-ontap/create-storage-vm.html["Créez une machine virtuelle de stockage"]
* link:https://docs.netapp.com/us-en/workload-setup-admin/use-codebox.html["Utiliser Terraform à partir de Codebox"^]




=== Recommandations de débit et d'IOPS dans le calculateur de stockage

Le calculateur de stockage fait des recommandations de configuration de système de fichiers FSX pour ONTAP pour le débit et les IOPS en fonction des bonnes pratiques AWS, qui vous guide de façon optimale pour votre sélection.



== 7 juillet 2024



=== Version initiale de Workload Factory pour Amazon FSX for NetApp ONTAP

Amazon FSX pour NetApp ONTAP est désormais disponible dans Workload Factory.
